{
  "hash": "4eee72400b78969d04f5dca10a018245",
  "result": {
    "markdown": "---\ntitle: \"Probability Theory\"\n---\n\n\n# Assignment 1 \n\n------------------------------------------------------------------------\n\n> Given Probabilities -\n $P(S) = 0.3$, \n $P(\\overline{S}) = 0.7$, \n $P(T/S) = 0.2$, \n $P(\\overline{T}/S) = 0.8$, \n $P(T/\\overline{S}) = 0.6$, \n $P(\\overline{T}/\\overline{S}) = 0.4$\n\n\n\n* $P(T\\cap S) = P(S) * P(T/S)$\n\n\n::: {.cell hash='01_probability_cache/html/unnamed-chunk-1_f2ebf6e97fc5f66e9cbf355546cfdec7'}\n\n```{.r .cell-code}\nP_T_and_S <- 0.3 * 0.2\nP_T_and_S\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n#> [1] 0.06\n```\n:::\n:::\n\n\n* $P(T\\cap \\overline{S}) = P(\\overline{S}) * P(T/\\overline{S})$\n\n\n::: {.cell hash='01_probability_cache/html/unnamed-chunk-2_c7e4ff6ac3d0405e6ac6202cad4ba771'}\n\n```{.r .cell-code}\nP_T_and_S_not <- 0.7 * 0.6\nP_T_and_S_not\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n#> [1] 0.42\n```\n:::\n:::\n\n\n* $P(\\overline{T}\\cap S) = P(S) * P(\\overline{T}/S)$\n\n\n::: {.cell hash='01_probability_cache/html/unnamed-chunk-3_2eec395fb416564d2f81ed011e9f2363'}\n\n```{.r .cell-code}\nP_not_T_and_S <- 0.3 * 0.8\nP_not_T_and_S\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n#> [1] 0.24\n```\n:::\n:::\n\n\n* $P(\\overline{T}\\cap \\overline{S}) = P(\\overline{S}) * P(\\overline{T}/\\overline{S})$\n\n\n::: {.cell hash='01_probability_cache/html/unnamed-chunk-4_1580656a8a4dcdb1f48f485c5a13be65'}\n\n```{.r .cell-code}\nP_not_T_and_S_not <- 0.7 * 0.4\nP_not_T_and_S_not\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n#> [1] 0.28\n```\n:::\n:::\n\n\n> Sum of all probabilities  \n\n\n::: {.cell hash='01_probability_cache/html/unnamed-chunk-5_e0d984668cd59ddf40a7f5f971289ada'}\n\n```{.r .cell-code}\nsum <- P_T_and_S + P_T_and_S_not + P_not_T_and_S + P_not_T_and_S_not\nsum\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n#> [1] 1\n```\n:::\n:::\n\n\n# Assignment 2\n\n------------------------------------------------------------------------\n\n* The percentage of customers using all three devices = 0.5%\n\n* The percentage of customers using at least two devices \n  = 7.3 + 3.3 + 8.8 + 0.5 = 19.9% \n\n* The percentage of customers using only one device \n  = 42.3 + 27.8 + 10 = 80.1%\n\n# Assignment 3\n\n------------------------------------------------------------------------\n\n> Given Probabilities - \n$P(B|A)=0.97$  \n$P(B|\\overline{A})=0.01$  \n$P(A)=0.04$\n\nBy Bayesian Theorem,\n$P(A|B) = \\frac{P(A|B)*P(A)}{P(B)} = \\frac{P(A|B)*P(A)}{P(B|A)*P(A)+P(B|\\overline{A})*P(\\overline{A})}$\n\n> Probability that the product is not faulty\n\n* $P(\\overline{A}|B)$\n\n\n::: {.cell hash='01_probability_cache/html/unnamed-chunk-6_7a60efd7ceea05f2ee5ee716811ef5de'}\n\n```{.r .cell-code}\nP_A_not_given_B = (0.01*0.96)/((0.01*0.96)+(0.97*0.04))\nP_A_not_given_B_percentage = P_A_not_given_B * 100\n\npaste(\"Probability that the product is not faulty -\", P_A_not_given_B_percentage, \"%\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n#> [1] \"Probability that the product is not faulty - 19.8347107438017 %\"\n```\n:::\n:::\n\n\n> Probability that the product is faulty\n\n* $P(A|B)$\n\n\n::: {.cell hash='01_probability_cache/html/unnamed-chunk-7_1c425b4363ea3ed9ee7f4e71b94cc347'}\n\n```{.r .cell-code}\nP_A_given_B = (0.97*0.04)/((0.01*0.96)+(0.97*0.04))\nP_A_given_B_percentage = P_A_given_B * 100\n\npaste(\"Probability that the product is faulty -\", P_A_given_B_percentage, \"%\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n#> [1] \"Probability that the product is faulty - 80.1652892561983 %\"\n```\n:::\n:::\n\n\nThese results show that in case the alarm is triggered, there is a possibility of about `19.83%` that the product is flawless and a probability of `80.17%` that the product is faulty.\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"../../site_libs/pagedtable-1.1/css/pagedtable.css\" rel=\"stylesheet\" />\r\n<script src=\"../../site_libs/pagedtable-1.1/js/pagedtable.js\"></script>\r\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}