{
  "hash": "1abfed7cc6d291652da39083a2ff29ba",
  "result": {
    "markdown": "---\ntitle: \"Directed Acyclic Graphs\"\n---\n\n\n# Parking Spot - DAG\n\n------------------------------------------------------------------------\n\n\n::: {.cell hash='05_dag_cache/html/unnamed-chunk-1_d15211cd75abf8b341803bcda6560ef4'}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(dagitty)\nlibrary(ggdag)\n\ndag <- 'dag {\nbb=\"0,0,1,1\"\nParking [exposure,pos=\"0.1,0.5\"]\nSales [outcome,pos=\"0.5,0.5\"]\nLocation [pos=\"0.3,1\"]\nParking -> Sales\nLocation -> Parking\nLocation -> Sales\n}\n'\nggdag_status(dag) + theme_dag()\n```\n\n::: {.cell-output-display}\n![](05_dag_files/figure-html/unnamed-chunk-1-1.png){width=672}\n:::\n:::\n\n\n# Data analysis\n\n------------------------------------------------------------------------\n\n> Loading the data frame\n\n\n::: {.cell hash='05_dag_cache/html/unnamed-chunk-2_c308fb527b5d3a0994a92db0e4c2c74f'}\n\n```{.r .cell-code}\ndf <- readRDS(\"Causal_Data_Science_Data/customer_sat.rds\")\n\nhead(df)\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"follow_ups\"],\"name\":[1],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"satisfaction\"],\"name\":[2],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"subscription\"],\"name\":[3],\"type\":[\"chr\"],\"align\":[\"left\"]}],\"data\":[{\"1\":\"8\",\"2\":\"40\",\"3\":\"Elite\"},{\"1\":\"7\",\"2\":\"45\",\"3\":\"Elite\"},{\"1\":\"8\",\"2\":\"47\",\"3\":\"Elite\"},{\"1\":\"9\",\"2\":\"44\",\"3\":\"Elite\"},{\"1\":\"10\",\"2\":\"50\",\"3\":\"Elite\"},{\"1\":\"6\",\"2\":\"55\",\"3\":\"Premium+\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n\n```{.r .cell-code}\n# Show table\ndf\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"follow_ups\"],\"name\":[1],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"satisfaction\"],\"name\":[2],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"subscription\"],\"name\":[3],\"type\":[\"chr\"],\"align\":[\"left\"]}],\"data\":[{\"1\":\"8\",\"2\":\"40\",\"3\":\"Elite\"},{\"1\":\"7\",\"2\":\"45\",\"3\":\"Elite\"},{\"1\":\"8\",\"2\":\"47\",\"3\":\"Elite\"},{\"1\":\"9\",\"2\":\"44\",\"3\":\"Elite\"},{\"1\":\"10\",\"2\":\"50\",\"3\":\"Elite\"},{\"1\":\"6\",\"2\":\"55\",\"3\":\"Premium+\"},{\"1\":\"7\",\"2\":\"60\",\"3\":\"Premium+\"},{\"1\":\"6\",\"2\":\"62\",\"3\":\"Premium+\"},{\"1\":\"8\",\"2\":\"59\",\"3\":\"Premium+\"},{\"1\":\"8\",\"2\":\"65\",\"3\":\"Premium+\"},{\"1\":\"0\",\"2\":\"70\",\"3\":\"Premium\"},{\"1\":\"1\",\"2\":\"74\",\"3\":\"Premium\"},{\"1\":\"2\",\"2\":\"77\",\"3\":\"Premium\"},{\"1\":\"2\",\"2\":\"74\",\"3\":\"Premium\"},{\"1\":\"3\",\"2\":\"80\",\"3\":\"Premium\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n\n```{.r .cell-code}\n# Get glimpse of data\nglimpse(df)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n#> Rows: 15\n#> Columns: 3\n#> $ follow_ups   <dbl> 8, 7, 8, 9, 10, 6, 7, 6, 8, 8, 0, 1, 2, 2, 3\n#> $ satisfaction <dbl> 40, 45, 47, 44, 50, 55, 60, 62, 59, 65, 70, 74, 77, 74, 80\n#> $ subscription <chr> \"Elite\", \"Elite\", \"Elite\", \"Elite\", \"Elite\", \"Premium+\", …\n```\n:::\n\n```{.r .cell-code}\nsummary(df, digits = 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n#>    follow_ups     satisfaction  subscription      \n#>  Min.   : 0.00   Min.   :40.0   Length:15         \n#>  1st Qu.: 2.50   1st Qu.:48.5   Class :character  \n#>  Median : 7.00   Median :60.0   Mode  :character  \n#>  Mean   : 5.67   Mean   :60.1                     \n#>  3rd Qu.: 8.00   3rd Qu.:72.0                     \n#>  Max.   :10.00   Max.   :80.0\n```\n:::\n\n```{.r .cell-code}\n# Select only numeric columns\ndf_numeric <- df[sapply(df, is.numeric)]\n\n# Calculate correlation matrix\ncor(df_numeric)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n#>              follow_ups satisfaction\n#> follow_ups    1.0000000   -0.8111461\n#> satisfaction -0.8111461    1.0000000\n```\n:::\n:::\n\n\n## 1. Regress satisfaction on follow_ups\n\n\n::: {.cell hash='05_dag_cache/html/unnamed-chunk-3_13bc8761ff7d94d326c7e1b161858d9b'}\n\n```{.r .cell-code}\nlm_model <- lm(satisfaction ~ follow_ups, data = df)\n\nsummary(lm_model)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n#> \n#> Call:\n#> lm(formula = satisfaction ~ follow_ups, data = df)\n#> \n#> Residuals:\n#>     Min      1Q  Median      3Q     Max \n#> -12.412  -5.257   1.733   4.506  12.588 \n#> \n#> Coefficients:\n#>             Estimate Std. Error t value Pr(>|t|)    \n#> (Intercept)  78.8860     4.2717  18.467 1.04e-10 ***\n#> follow_ups   -3.3093     0.6618  -5.001 0.000243 ***\n#> ---\n#> Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n#> \n#> Residual standard error: 7.923 on 13 degrees of freedom\n#> Multiple R-squared:  0.658,\tAdjusted R-squared:  0.6316 \n#> F-statistic: 25.01 on 1 and 13 DF,  p-value: 0.0002427\n```\n:::\n:::\n\n\n## 2. Regress satisfaction on follow_ups and account for subscription\n\n\n::: {.cell hash='05_dag_cache/html/unnamed-chunk-4_dcc668b3c6a25d137f5595f8e4d0ed52'}\n\n```{.r .cell-code}\nlm_model_subscription <- lm(satisfaction ~ ., data = df)\n\nsummary(lm_model_subscription)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n#> \n#> Call:\n#> lm(formula = satisfaction ~ ., data = df)\n#> \n#> Residuals:\n#>     Min      1Q  Median      3Q     Max \n#> -4.3222 -2.1972  0.3167  2.2667  3.9944 \n#> \n#> Coefficients:\n#>                      Estimate Std. Error t value Pr(>|t|)    \n#> (Intercept)           26.7667     6.6804   4.007  0.00206 ** \n#> follow_ups             2.1944     0.7795   2.815  0.01682 *  \n#> subscriptionPremium   44.7222     5.6213   7.956 6.88e-06 ***\n#> subscriptionPremium+  18.0722     2.1659   8.344 4.37e-06 ***\n#> ---\n#> Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n#> \n#> Residual standard error: 2.958 on 11 degrees of freedom\n#> Multiple R-squared:  0.9597,\tAdjusted R-squared:  0.9487 \n#> F-statistic: 87.21 on 3 and 11 DF,  p-value: 5.956e-08\n```\n:::\n:::\n\n\n# Compare the coefficients and find a possible explanation.\n\n* In the model **without a subscription**, the coefficient is **-3.3093**, indicating that without a subscription, follow-ups decrease customer satisfaction. Conversely, in the model **with a subscription**, the coefficient is **2.1944**, suggesting that with a subscription, follow-ups increase customer satisfaction. The coefficients for **Premium** and **Premium+** are +44.7222 and +18.0722, respectively, signifying that being on these subscription levels is associated with substantial increases in satisfaction compared to the base category. I believe customers find it intrusive when they are followed up without any subscription, potentially due to having fewer features. On the other hand, premium and elite customers seem to perceive the follow-ups more positively. This impact is also reflected in the variance R^2^ and R^2^ (Adjusted), where both values increased, indicating that the model now better explains the variance in satisfaction, highlighting the significance of subscription level in understanding customer satisfaction.\n\n\n# Plot the data\n\n## Without Conditioning on Subscription\n\n\n::: {.cell hash='05_dag_cache/html/unnamed-chunk-5_f6e0de10836e74653f313b4f98028bd1'}\n\n```{.r .cell-code}\nsimps_not_cond  <- ggplot(df, aes(x = follow_ups, y = satisfaction)) +\n  geom_point(alpha = .8) +\n  stat_smooth(method = \"lm\", se = F)\n\nsimps_not_cond\n```\n\n::: {.cell-output .cell-output-stderr}\n```\n#> `geom_smooth()` using formula = 'y ~ x'\n```\n:::\n\n::: {.cell-output-display}\n![](05_dag_files/figure-html/unnamed-chunk-5-1.png){width=672}\n:::\n:::\n\n\n## Conditioning on Subscription\n\n\n::: {.cell hash='05_dag_cache/html/unnamed-chunk-6_d230ad5e2af487d4db0073f6fa596ed0'}\n\n```{.r .cell-code}\nsimps_cond <- ggplot(df, aes(x = follow_ups, y = satisfaction, color = subscription )) +\n  geom_point(alpha = .8) +\n  stat_smooth(method = \"lm\", se = F) +\n  theme(legend.position = \"right\")\n\nsimps_cond \n```\n\n::: {.cell-output .cell-output-stderr}\n```\n#> `geom_smooth()` using formula = 'y ~ x'\n```\n:::\n\n::: {.cell-output-display}\n![](05_dag_files/figure-html/unnamed-chunk-6-1.png){width=672}\n:::\n:::\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"../../site_libs/pagedtable-1.1/css/pagedtable.css\" rel=\"stylesheet\" />\r\n<script src=\"../../site_libs/pagedtable-1.1/js/pagedtable.js\"></script>\r\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}