{
  "hash": "36e8e55794e99758f3de87308fe24e91",
  "result": {
    "markdown": "---\ntitle: \"Regression and Statistical Inference\"\n---\n\n\n# Task 1\n\n------------------------------------------------------------------------\n\n> Loading the data set\n\n\n::: {.cell hash='03_regression_cache/html/unnamed-chunk-1_dfb722d504099b11774346bf92fe32d0'}\n\n```{.r .cell-code}\ndf <- readRDS(\"Causal_Data_Science_Data/car_prices.rds\")\n```\n:::\n\n> Checking the dimensions of the dataset\n\n\n::: {.cell hash='03_regression_cache/html/unnamed-chunk-2_7cff25b5510b3c491ffa63a0d487220e'}\n\n```{.r .cell-code}\ndimensions <- dim(df)\npaste(\"Dimensions of the dataset =\", dimensions)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n#> [1] \"Dimensions of the dataset = 181\" \"Dimensions of the dataset = 22\"\n```\n:::\n:::\n\n\n# Task 2\n\n------------------------------------------------------------------------\n\n\n::: {.cell hash='03_regression_cache/html/unnamed-chunk-3_6042a7d2892217834c1a69125954ea66'}\n\n```{.r .cell-code}\nhead(df)\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"aspiration\"],\"name\":[1],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"doornumber\"],\"name\":[2],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"carbody\"],\"name\":[3],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"drivewheel\"],\"name\":[4],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"enginelocation\"],\"name\":[5],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"wheelbase\"],\"name\":[6],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"carlength\"],\"name\":[7],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"carwidth\"],\"name\":[8],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"carheight\"],\"name\":[9],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"curbweight\"],\"name\":[10],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"enginetype\"],\"name\":[11],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"cylindernumber\"],\"name\":[12],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"enginesize\"],\"name\":[13],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"fuelsystem\"],\"name\":[14],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"boreratio\"],\"name\":[15],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"stroke\"],\"name\":[16],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"compressionratio\"],\"name\":[17],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"horsepower\"],\"name\":[18],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"peakrpm\"],\"name\":[19],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"citympg\"],\"name\":[20],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"highwaympg\"],\"name\":[21],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"price\"],\"name\":[22],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"std\",\"2\":\"two\",\"3\":\"convertible\",\"4\":\"rwd\",\"5\":\"front\",\"6\":\"88.6\",\"7\":\"168.8\",\"8\":\"64.1\",\"9\":\"48.8\",\"10\":\"2548\",\"11\":\"dohc\",\"12\":\"four\",\"13\":\"130\",\"14\":\"mpfi\",\"15\":\"3.47\",\"16\":\"2.68\",\"17\":\"9.0\",\"18\":\"111\",\"19\":\"5000\",\"20\":\"21\",\"21\":\"27\",\"22\":\"13495\"},{\"1\":\"std\",\"2\":\"two\",\"3\":\"convertible\",\"4\":\"rwd\",\"5\":\"front\",\"6\":\"88.6\",\"7\":\"168.8\",\"8\":\"64.1\",\"9\":\"48.8\",\"10\":\"2548\",\"11\":\"dohc\",\"12\":\"four\",\"13\":\"130\",\"14\":\"mpfi\",\"15\":\"3.47\",\"16\":\"2.68\",\"17\":\"9.0\",\"18\":\"111\",\"19\":\"5000\",\"20\":\"21\",\"21\":\"27\",\"22\":\"16500\"},{\"1\":\"std\",\"2\":\"two\",\"3\":\"hatchback\",\"4\":\"rwd\",\"5\":\"front\",\"6\":\"94.5\",\"7\":\"171.2\",\"8\":\"65.5\",\"9\":\"52.4\",\"10\":\"2823\",\"11\":\"ohcv\",\"12\":\"six\",\"13\":\"152\",\"14\":\"mpfi\",\"15\":\"2.68\",\"16\":\"3.47\",\"17\":\"9.0\",\"18\":\"154\",\"19\":\"5000\",\"20\":\"19\",\"21\":\"26\",\"22\":\"16500\"},{\"1\":\"std\",\"2\":\"four\",\"3\":\"sedan\",\"4\":\"fwd\",\"5\":\"front\",\"6\":\"99.8\",\"7\":\"176.6\",\"8\":\"66.2\",\"9\":\"54.3\",\"10\":\"2337\",\"11\":\"ohc\",\"12\":\"four\",\"13\":\"109\",\"14\":\"mpfi\",\"15\":\"3.19\",\"16\":\"3.40\",\"17\":\"10.0\",\"18\":\"102\",\"19\":\"5500\",\"20\":\"24\",\"21\":\"30\",\"22\":\"13950\"},{\"1\":\"std\",\"2\":\"four\",\"3\":\"sedan\",\"4\":\"4wd\",\"5\":\"front\",\"6\":\"99.4\",\"7\":\"176.6\",\"8\":\"66.4\",\"9\":\"54.3\",\"10\":\"2824\",\"11\":\"ohc\",\"12\":\"five\",\"13\":\"136\",\"14\":\"mpfi\",\"15\":\"3.19\",\"16\":\"3.40\",\"17\":\"8.0\",\"18\":\"115\",\"19\":\"5500\",\"20\":\"18\",\"21\":\"22\",\"22\":\"17450\"},{\"1\":\"std\",\"2\":\"two\",\"3\":\"sedan\",\"4\":\"fwd\",\"5\":\"front\",\"6\":\"99.8\",\"7\":\"177.3\",\"8\":\"66.3\",\"9\":\"53.1\",\"10\":\"2507\",\"11\":\"ohc\",\"12\":\"five\",\"13\":\"136\",\"14\":\"mpfi\",\"15\":\"3.19\",\"16\":\"3.40\",\"17\":\"8.5\",\"18\":\"110\",\"19\":\"5500\",\"20\":\"19\",\"21\":\"25\",\"22\":\"15250\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n\n```{.r .cell-code}\n# Show table\ndf\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"aspiration\"],\"name\":[1],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"doornumber\"],\"name\":[2],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"carbody\"],\"name\":[3],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"drivewheel\"],\"name\":[4],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"enginelocation\"],\"name\":[5],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"wheelbase\"],\"name\":[6],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"carlength\"],\"name\":[7],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"carwidth\"],\"name\":[8],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"carheight\"],\"name\":[9],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"curbweight\"],\"name\":[10],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"enginetype\"],\"name\":[11],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"cylindernumber\"],\"name\":[12],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"enginesize\"],\"name\":[13],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"fuelsystem\"],\"name\":[14],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"boreratio\"],\"name\":[15],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"stroke\"],\"name\":[16],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"compressionratio\"],\"name\":[17],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"horsepower\"],\"name\":[18],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"peakrpm\"],\"name\":[19],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"citympg\"],\"name\":[20],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"highwaympg\"],\"name\":[21],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"price\"],\"name\":[22],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"std\",\"2\":\"two\",\"3\":\"convertible\",\"4\":\"rwd\",\"5\":\"front\",\"6\":\"88.6\",\"7\":\"168.8\",\"8\":\"64.1\",\"9\":\"48.8\",\"10\":\"2548\",\"11\":\"dohc\",\"12\":\"four\",\"13\":\"130\",\"14\":\"mpfi\",\"15\":\"3.47\",\"16\":\"2.68\",\"17\":\"9.00\",\"18\":\"111\",\"19\":\"5000\",\"20\":\"21\",\"21\":\"27\",\"22\":\"13495.00\"},{\"1\":\"std\",\"2\":\"two\",\"3\":\"convertible\",\"4\":\"rwd\",\"5\":\"front\",\"6\":\"88.6\",\"7\":\"168.8\",\"8\":\"64.1\",\"9\":\"48.8\",\"10\":\"2548\",\"11\":\"dohc\",\"12\":\"four\",\"13\":\"130\",\"14\":\"mpfi\",\"15\":\"3.47\",\"16\":\"2.68\",\"17\":\"9.00\",\"18\":\"111\",\"19\":\"5000\",\"20\":\"21\",\"21\":\"27\",\"22\":\"16500.00\"},{\"1\":\"std\",\"2\":\"two\",\"3\":\"hatchback\",\"4\":\"rwd\",\"5\":\"front\",\"6\":\"94.5\",\"7\":\"171.2\",\"8\":\"65.5\",\"9\":\"52.4\",\"10\":\"2823\",\"11\":\"ohcv\",\"12\":\"six\",\"13\":\"152\",\"14\":\"mpfi\",\"15\":\"2.68\",\"16\":\"3.47\",\"17\":\"9.00\",\"18\":\"154\",\"19\":\"5000\",\"20\":\"19\",\"21\":\"26\",\"22\":\"16500.00\"},{\"1\":\"std\",\"2\":\"four\",\"3\":\"sedan\",\"4\":\"fwd\",\"5\":\"front\",\"6\":\"99.8\",\"7\":\"176.6\",\"8\":\"66.2\",\"9\":\"54.3\",\"10\":\"2337\",\"11\":\"ohc\",\"12\":\"four\",\"13\":\"109\",\"14\":\"mpfi\",\"15\":\"3.19\",\"16\":\"3.40\",\"17\":\"10.00\",\"18\":\"102\",\"19\":\"5500\",\"20\":\"24\",\"21\":\"30\",\"22\":\"13950.00\"},{\"1\":\"std\",\"2\":\"four\",\"3\":\"sedan\",\"4\":\"4wd\",\"5\":\"front\",\"6\":\"99.4\",\"7\":\"176.6\",\"8\":\"66.4\",\"9\":\"54.3\",\"10\":\"2824\",\"11\":\"ohc\",\"12\":\"five\",\"13\":\"136\",\"14\":\"mpfi\",\"15\":\"3.19\",\"16\":\"3.40\",\"17\":\"8.00\",\"18\":\"115\",\"19\":\"5500\",\"20\":\"18\",\"21\":\"22\",\"22\":\"17450.00\"},{\"1\":\"std\",\"2\":\"two\",\"3\":\"sedan\",\"4\":\"fwd\",\"5\":\"front\",\"6\":\"99.8\",\"7\":\"177.3\",\"8\":\"66.3\",\"9\":\"53.1\",\"10\":\"2507\",\"11\":\"ohc\",\"12\":\"five\",\"13\":\"136\",\"14\":\"mpfi\",\"15\":\"3.19\",\"16\":\"3.40\",\"17\":\"8.50\",\"18\":\"110\",\"19\":\"5500\",\"20\":\"19\",\"21\":\"25\",\"22\":\"15250.00\"},{\"1\":\"std\",\"2\":\"four\",\"3\":\"sedan\",\"4\":\"fwd\",\"5\":\"front\",\"6\":\"105.8\",\"7\":\"192.7\",\"8\":\"71.4\",\"9\":\"55.7\",\"10\":\"2844\",\"11\":\"ohc\",\"12\":\"five\",\"13\":\"136\",\"14\":\"mpfi\",\"15\":\"3.19\",\"16\":\"3.40\",\"17\":\"8.50\",\"18\":\"110\",\"19\":\"5500\",\"20\":\"19\",\"21\":\"25\",\"22\":\"17710.00\"},{\"1\":\"std\",\"2\":\"four\",\"3\":\"wagon\",\"4\":\"fwd\",\"5\":\"front\",\"6\":\"105.8\",\"7\":\"192.7\",\"8\":\"71.4\",\"9\":\"55.7\",\"10\":\"2954\",\"11\":\"ohc\",\"12\":\"five\",\"13\":\"136\",\"14\":\"mpfi\",\"15\":\"3.19\",\"16\":\"3.40\",\"17\":\"8.50\",\"18\":\"110\",\"19\":\"5500\",\"20\":\"19\",\"21\":\"25\",\"22\":\"18920.00\"},{\"1\":\"turbo\",\"2\":\"four\",\"3\":\"sedan\",\"4\":\"fwd\",\"5\":\"front\",\"6\":\"105.8\",\"7\":\"192.7\",\"8\":\"71.4\",\"9\":\"55.9\",\"10\":\"3086\",\"11\":\"ohc\",\"12\":\"five\",\"13\":\"131\",\"14\":\"mpfi\",\"15\":\"3.13\",\"16\":\"3.40\",\"17\":\"8.30\",\"18\":\"140\",\"19\":\"5500\",\"20\":\"17\",\"21\":\"20\",\"22\":\"23875.00\"},{\"1\":\"turbo\",\"2\":\"two\",\"3\":\"hatchback\",\"4\":\"4wd\",\"5\":\"front\",\"6\":\"99.5\",\"7\":\"178.2\",\"8\":\"67.9\",\"9\":\"52.0\",\"10\":\"3053\",\"11\":\"ohc\",\"12\":\"five\",\"13\":\"131\",\"14\":\"mpfi\",\"15\":\"3.13\",\"16\":\"3.40\",\"17\":\"7.00\",\"18\":\"160\",\"19\":\"5500\",\"20\":\"16\",\"21\":\"22\",\"22\":\"17859.17\"},{\"1\":\"std\",\"2\":\"two\",\"3\":\"sedan\",\"4\":\"rwd\",\"5\":\"front\",\"6\":\"101.2\",\"7\":\"176.8\",\"8\":\"64.8\",\"9\":\"54.3\",\"10\":\"2395\",\"11\":\"ohc\",\"12\":\"four\",\"13\":\"108\",\"14\":\"mpfi\",\"15\":\"3.50\",\"16\":\"2.80\",\"17\":\"8.80\",\"18\":\"101\",\"19\":\"5800\",\"20\":\"23\",\"21\":\"29\",\"22\":\"16430.00\"},{\"1\":\"std\",\"2\":\"four\",\"3\":\"sedan\",\"4\":\"rwd\",\"5\":\"front\",\"6\":\"101.2\",\"7\":\"176.8\",\"8\":\"64.8\",\"9\":\"54.3\",\"10\":\"2395\",\"11\":\"ohc\",\"12\":\"four\",\"13\":\"108\",\"14\":\"mpfi\",\"15\":\"3.50\",\"16\":\"2.80\",\"17\":\"8.80\",\"18\":\"101\",\"19\":\"5800\",\"20\":\"23\",\"21\":\"29\",\"22\":\"16925.00\"},{\"1\":\"std\",\"2\":\"two\",\"3\":\"sedan\",\"4\":\"rwd\",\"5\":\"front\",\"6\":\"101.2\",\"7\":\"176.8\",\"8\":\"64.8\",\"9\":\"54.3\",\"10\":\"2710\",\"11\":\"ohc\",\"12\":\"six\",\"13\":\"164\",\"14\":\"mpfi\",\"15\":\"3.31\",\"16\":\"3.19\",\"17\":\"9.00\",\"18\":\"121\",\"19\":\"4250\",\"20\":\"21\",\"21\":\"28\",\"22\":\"20970.00\"},{\"1\":\"std\",\"2\":\"four\",\"3\":\"sedan\",\"4\":\"rwd\",\"5\":\"front\",\"6\":\"101.2\",\"7\":\"176.8\",\"8\":\"64.8\",\"9\":\"54.3\",\"10\":\"2765\",\"11\":\"ohc\",\"12\":\"six\",\"13\":\"164\",\"14\":\"mpfi\",\"15\":\"3.31\",\"16\":\"3.19\",\"17\":\"9.00\",\"18\":\"121\",\"19\":\"4250\",\"20\":\"21\",\"21\":\"28\",\"22\":\"21105.00\"},{\"1\":\"std\",\"2\":\"four\",\"3\":\"sedan\",\"4\":\"rwd\",\"5\":\"front\",\"6\":\"103.5\",\"7\":\"189.0\",\"8\":\"66.9\",\"9\":\"55.7\",\"10\":\"3055\",\"11\":\"ohc\",\"12\":\"six\",\"13\":\"164\",\"14\":\"mpfi\",\"15\":\"3.31\",\"16\":\"3.19\",\"17\":\"9.00\",\"18\":\"121\",\"19\":\"4250\",\"20\":\"20\",\"21\":\"25\",\"22\":\"24565.00\"},{\"1\":\"std\",\"2\":\"four\",\"3\":\"sedan\",\"4\":\"rwd\",\"5\":\"front\",\"6\":\"103.5\",\"7\":\"189.0\",\"8\":\"66.9\",\"9\":\"55.7\",\"10\":\"3230\",\"11\":\"ohc\",\"12\":\"six\",\"13\":\"209\",\"14\":\"mpfi\",\"15\":\"3.62\",\"16\":\"3.39\",\"17\":\"8.00\",\"18\":\"182\",\"19\":\"5400\",\"20\":\"16\",\"21\":\"22\",\"22\":\"30760.00\"},{\"1\":\"std\",\"2\":\"two\",\"3\":\"sedan\",\"4\":\"rwd\",\"5\":\"front\",\"6\":\"103.5\",\"7\":\"193.8\",\"8\":\"67.9\",\"9\":\"53.7\",\"10\":\"3380\",\"11\":\"ohc\",\"12\":\"six\",\"13\":\"209\",\"14\":\"mpfi\",\"15\":\"3.62\",\"16\":\"3.39\",\"17\":\"8.00\",\"18\":\"182\",\"19\":\"5400\",\"20\":\"16\",\"21\":\"22\",\"22\":\"41315.00\"},{\"1\":\"std\",\"2\":\"four\",\"3\":\"sedan\",\"4\":\"rwd\",\"5\":\"front\",\"6\":\"110.0\",\"7\":\"197.0\",\"8\":\"70.9\",\"9\":\"56.3\",\"10\":\"3505\",\"11\":\"ohc\",\"12\":\"six\",\"13\":\"209\",\"14\":\"mpfi\",\"15\":\"3.62\",\"16\":\"3.39\",\"17\":\"8.00\",\"18\":\"182\",\"19\":\"5400\",\"20\":\"15\",\"21\":\"20\",\"22\":\"36880.00\"},{\"1\":\"std\",\"2\":\"two\",\"3\":\"hatchback\",\"4\":\"fwd\",\"5\":\"front\",\"6\":\"88.4\",\"7\":\"141.1\",\"8\":\"60.3\",\"9\":\"53.2\",\"10\":\"1488\",\"11\":\"l\",\"12\":\"three\",\"13\":\"61\",\"14\":\"2bbl\",\"15\":\"2.91\",\"16\":\"3.03\",\"17\":\"9.50\",\"18\":\"48\",\"19\":\"5100\",\"20\":\"47\",\"21\":\"53\",\"22\":\"5151.00\"},{\"1\":\"std\",\"2\":\"two\",\"3\":\"hatchback\",\"4\":\"fwd\",\"5\":\"front\",\"6\":\"94.5\",\"7\":\"155.9\",\"8\":\"63.6\",\"9\":\"52.0\",\"10\":\"1874\",\"11\":\"ohc\",\"12\":\"four\",\"13\":\"90\",\"14\":\"2bbl\",\"15\":\"3.03\",\"16\":\"3.11\",\"17\":\"9.60\",\"18\":\"70\",\"19\":\"5400\",\"20\":\"38\",\"21\":\"43\",\"22\":\"6295.00\"},{\"1\":\"std\",\"2\":\"four\",\"3\":\"sedan\",\"4\":\"fwd\",\"5\":\"front\",\"6\":\"94.5\",\"7\":\"158.8\",\"8\":\"63.6\",\"9\":\"52.0\",\"10\":\"1909\",\"11\":\"ohc\",\"12\":\"four\",\"13\":\"90\",\"14\":\"2bbl\",\"15\":\"3.03\",\"16\":\"3.11\",\"17\":\"9.60\",\"18\":\"70\",\"19\":\"5400\",\"20\":\"38\",\"21\":\"43\",\"22\":\"6575.00\"},{\"1\":\"std\",\"2\":\"two\",\"3\":\"hatchback\",\"4\":\"fwd\",\"5\":\"front\",\"6\":\"93.7\",\"7\":\"157.3\",\"8\":\"63.8\",\"9\":\"50.8\",\"10\":\"1876\",\"11\":\"ohc\",\"12\":\"four\",\"13\":\"90\",\"14\":\"2bbl\",\"15\":\"2.97\",\"16\":\"3.23\",\"17\":\"9.41\",\"18\":\"68\",\"19\":\"5500\",\"20\":\"37\",\"21\":\"41\",\"22\":\"5572.00\"},{\"1\":\"std\",\"2\":\"two\",\"3\":\"hatchback\",\"4\":\"fwd\",\"5\":\"front\",\"6\":\"93.7\",\"7\":\"157.3\",\"8\":\"63.8\",\"9\":\"50.8\",\"10\":\"1876\",\"11\":\"ohc\",\"12\":\"four\",\"13\":\"90\",\"14\":\"2bbl\",\"15\":\"2.97\",\"16\":\"3.23\",\"17\":\"9.40\",\"18\":\"68\",\"19\":\"5500\",\"20\":\"31\",\"21\":\"38\",\"22\":\"6377.00\"},{\"1\":\"turbo\",\"2\":\"two\",\"3\":\"hatchback\",\"4\":\"fwd\",\"5\":\"front\",\"6\":\"93.7\",\"7\":\"157.3\",\"8\":\"63.8\",\"9\":\"50.8\",\"10\":\"2128\",\"11\":\"ohc\",\"12\":\"four\",\"13\":\"98\",\"14\":\"mpfi\",\"15\":\"3.03\",\"16\":\"3.39\",\"17\":\"7.60\",\"18\":\"102\",\"19\":\"5500\",\"20\":\"24\",\"21\":\"30\",\"22\":\"7957.00\"},{\"1\":\"std\",\"2\":\"four\",\"3\":\"hatchback\",\"4\":\"fwd\",\"5\":\"front\",\"6\":\"93.7\",\"7\":\"157.3\",\"8\":\"63.8\",\"9\":\"50.6\",\"10\":\"1967\",\"11\":\"ohc\",\"12\":\"four\",\"13\":\"90\",\"14\":\"2bbl\",\"15\":\"2.97\",\"16\":\"3.23\",\"17\":\"9.40\",\"18\":\"68\",\"19\":\"5500\",\"20\":\"31\",\"21\":\"38\",\"22\":\"6229.00\"},{\"1\":\"std\",\"2\":\"four\",\"3\":\"sedan\",\"4\":\"fwd\",\"5\":\"front\",\"6\":\"93.7\",\"7\":\"157.3\",\"8\":\"63.8\",\"9\":\"50.6\",\"10\":\"1989\",\"11\":\"ohc\",\"12\":\"four\",\"13\":\"90\",\"14\":\"2bbl\",\"15\":\"2.97\",\"16\":\"3.23\",\"17\":\"9.40\",\"18\":\"68\",\"19\":\"5500\",\"20\":\"31\",\"21\":\"38\",\"22\":\"6692.00\"},{\"1\":\"std\",\"2\":\"four\",\"3\":\"sedan\",\"4\":\"fwd\",\"5\":\"front\",\"6\":\"93.7\",\"7\":\"157.3\",\"8\":\"63.8\",\"9\":\"50.6\",\"10\":\"1989\",\"11\":\"ohc\",\"12\":\"four\",\"13\":\"90\",\"14\":\"2bbl\",\"15\":\"2.97\",\"16\":\"3.23\",\"17\":\"9.40\",\"18\":\"68\",\"19\":\"5500\",\"20\":\"31\",\"21\":\"38\",\"22\":\"7609.00\"},{\"1\":\"turbo\",\"2\":\"two\",\"3\":\"sedan\",\"4\":\"fwd\",\"5\":\"front\",\"6\":\"93.7\",\"7\":\"157.3\",\"8\":\"63.8\",\"9\":\"50.6\",\"10\":\"2191\",\"11\":\"ohc\",\"12\":\"four\",\"13\":\"98\",\"14\":\"mpfi\",\"15\":\"3.03\",\"16\":\"3.39\",\"17\":\"7.60\",\"18\":\"102\",\"19\":\"5500\",\"20\":\"24\",\"21\":\"30\",\"22\":\"8558.00\"},{\"1\":\"std\",\"2\":\"four\",\"3\":\"wagon\",\"4\":\"fwd\",\"5\":\"front\",\"6\":\"103.3\",\"7\":\"174.6\",\"8\":\"64.6\",\"9\":\"59.8\",\"10\":\"2535\",\"11\":\"ohc\",\"12\":\"four\",\"13\":\"122\",\"14\":\"2bbl\",\"15\":\"3.34\",\"16\":\"3.46\",\"17\":\"8.50\",\"18\":\"88\",\"19\":\"5000\",\"20\":\"24\",\"21\":\"30\",\"22\":\"8921.00\"},{\"1\":\"turbo\",\"2\":\"two\",\"3\":\"hatchback\",\"4\":\"fwd\",\"5\":\"front\",\"6\":\"95.9\",\"7\":\"173.2\",\"8\":\"66.3\",\"9\":\"50.2\",\"10\":\"2811\",\"11\":\"ohc\",\"12\":\"four\",\"13\":\"156\",\"14\":\"mfi\",\"15\":\"3.60\",\"16\":\"3.90\",\"17\":\"7.00\",\"18\":\"145\",\"19\":\"5000\",\"20\":\"19\",\"21\":\"24\",\"22\":\"12964.00\"},{\"1\":\"std\",\"2\":\"two\",\"3\":\"hatchback\",\"4\":\"fwd\",\"5\":\"front\",\"6\":\"86.6\",\"7\":\"144.6\",\"8\":\"63.9\",\"9\":\"50.8\",\"10\":\"1713\",\"11\":\"ohc\",\"12\":\"four\",\"13\":\"92\",\"14\":\"1bbl\",\"15\":\"2.91\",\"16\":\"3.41\",\"17\":\"9.60\",\"18\":\"58\",\"19\":\"4800\",\"20\":\"49\",\"21\":\"54\",\"22\":\"6479.00\"},{\"1\":\"std\",\"2\":\"two\",\"3\":\"hatchback\",\"4\":\"fwd\",\"5\":\"front\",\"6\":\"86.6\",\"7\":\"144.6\",\"8\":\"63.9\",\"9\":\"50.8\",\"10\":\"1819\",\"11\":\"ohc\",\"12\":\"four\",\"13\":\"92\",\"14\":\"1bbl\",\"15\":\"2.91\",\"16\":\"3.41\",\"17\":\"9.20\",\"18\":\"76\",\"19\":\"6000\",\"20\":\"31\",\"21\":\"38\",\"22\":\"6855.00\"},{\"1\":\"std\",\"2\":\"two\",\"3\":\"hatchback\",\"4\":\"fwd\",\"5\":\"front\",\"6\":\"93.7\",\"7\":\"150.0\",\"8\":\"64.0\",\"9\":\"52.6\",\"10\":\"1837\",\"11\":\"ohc\",\"12\":\"four\",\"13\":\"79\",\"14\":\"1bbl\",\"15\":\"2.91\",\"16\":\"3.07\",\"17\":\"10.10\",\"18\":\"60\",\"19\":\"5500\",\"20\":\"38\",\"21\":\"42\",\"22\":\"5399.00\"},{\"1\":\"std\",\"2\":\"two\",\"3\":\"hatchback\",\"4\":\"fwd\",\"5\":\"front\",\"6\":\"93.7\",\"7\":\"150.0\",\"8\":\"64.0\",\"9\":\"52.6\",\"10\":\"1940\",\"11\":\"ohc\",\"12\":\"four\",\"13\":\"92\",\"14\":\"1bbl\",\"15\":\"2.91\",\"16\":\"3.41\",\"17\":\"9.20\",\"18\":\"76\",\"19\":\"6000\",\"20\":\"30\",\"21\":\"34\",\"22\":\"6529.00\"},{\"1\":\"std\",\"2\":\"two\",\"3\":\"hatchback\",\"4\":\"fwd\",\"5\":\"front\",\"6\":\"93.7\",\"7\":\"150.0\",\"8\":\"64.0\",\"9\":\"52.6\",\"10\":\"1956\",\"11\":\"ohc\",\"12\":\"four\",\"13\":\"92\",\"14\":\"1bbl\",\"15\":\"2.91\",\"16\":\"3.41\",\"17\":\"9.20\",\"18\":\"76\",\"19\":\"6000\",\"20\":\"30\",\"21\":\"34\",\"22\":\"7129.00\"},{\"1\":\"std\",\"2\":\"four\",\"3\":\"sedan\",\"4\":\"fwd\",\"5\":\"front\",\"6\":\"96.5\",\"7\":\"163.4\",\"8\":\"64.0\",\"9\":\"54.5\",\"10\":\"2010\",\"11\":\"ohc\",\"12\":\"four\",\"13\":\"92\",\"14\":\"1bbl\",\"15\":\"2.91\",\"16\":\"3.41\",\"17\":\"9.20\",\"18\":\"76\",\"19\":\"6000\",\"20\":\"30\",\"21\":\"34\",\"22\":\"7295.00\"},{\"1\":\"std\",\"2\":\"four\",\"3\":\"wagon\",\"4\":\"fwd\",\"5\":\"front\",\"6\":\"96.5\",\"7\":\"157.1\",\"8\":\"63.9\",\"9\":\"58.3\",\"10\":\"2024\",\"11\":\"ohc\",\"12\":\"four\",\"13\":\"92\",\"14\":\"1bbl\",\"15\":\"2.92\",\"16\":\"3.41\",\"17\":\"9.20\",\"18\":\"76\",\"19\":\"6000\",\"20\":\"30\",\"21\":\"34\",\"22\":\"7295.00\"},{\"1\":\"std\",\"2\":\"two\",\"3\":\"hatchback\",\"4\":\"fwd\",\"5\":\"front\",\"6\":\"96.5\",\"7\":\"167.5\",\"8\":\"65.2\",\"9\":\"53.3\",\"10\":\"2236\",\"11\":\"ohc\",\"12\":\"four\",\"13\":\"110\",\"14\":\"1bbl\",\"15\":\"3.15\",\"16\":\"3.58\",\"17\":\"9.00\",\"18\":\"86\",\"19\":\"5800\",\"20\":\"27\",\"21\":\"33\",\"22\":\"7895.00\"},{\"1\":\"std\",\"2\":\"two\",\"3\":\"hatchback\",\"4\":\"fwd\",\"5\":\"front\",\"6\":\"96.5\",\"7\":\"167.5\",\"8\":\"65.2\",\"9\":\"53.3\",\"10\":\"2289\",\"11\":\"ohc\",\"12\":\"four\",\"13\":\"110\",\"14\":\"1bbl\",\"15\":\"3.15\",\"16\":\"3.58\",\"17\":\"9.00\",\"18\":\"86\",\"19\":\"5800\",\"20\":\"27\",\"21\":\"33\",\"22\":\"9095.00\"},{\"1\":\"std\",\"2\":\"four\",\"3\":\"sedan\",\"4\":\"fwd\",\"5\":\"front\",\"6\":\"96.5\",\"7\":\"175.4\",\"8\":\"65.2\",\"9\":\"54.1\",\"10\":\"2304\",\"11\":\"ohc\",\"12\":\"four\",\"13\":\"110\",\"14\":\"1bbl\",\"15\":\"3.15\",\"16\":\"3.58\",\"17\":\"9.00\",\"18\":\"86\",\"19\":\"5800\",\"20\":\"27\",\"21\":\"33\",\"22\":\"8845.00\"},{\"1\":\"std\",\"2\":\"four\",\"3\":\"sedan\",\"4\":\"fwd\",\"5\":\"front\",\"6\":\"96.5\",\"7\":\"175.4\",\"8\":\"62.5\",\"9\":\"54.1\",\"10\":\"2372\",\"11\":\"ohc\",\"12\":\"four\",\"13\":\"110\",\"14\":\"1bbl\",\"15\":\"3.15\",\"16\":\"3.58\",\"17\":\"9.00\",\"18\":\"86\",\"19\":\"5800\",\"20\":\"27\",\"21\":\"33\",\"22\":\"10295.00\"},{\"1\":\"std\",\"2\":\"four\",\"3\":\"sedan\",\"4\":\"fwd\",\"5\":\"front\",\"6\":\"96.5\",\"7\":\"175.4\",\"8\":\"65.2\",\"9\":\"54.1\",\"10\":\"2465\",\"11\":\"ohc\",\"12\":\"four\",\"13\":\"110\",\"14\":\"mpfi\",\"15\":\"3.15\",\"16\":\"3.58\",\"17\":\"9.00\",\"18\":\"101\",\"19\":\"5800\",\"20\":\"24\",\"21\":\"28\",\"22\":\"12945.00\"},{\"1\":\"std\",\"2\":\"two\",\"3\":\"sedan\",\"4\":\"fwd\",\"5\":\"front\",\"6\":\"96.5\",\"7\":\"169.1\",\"8\":\"66.0\",\"9\":\"51.0\",\"10\":\"2293\",\"11\":\"ohc\",\"12\":\"four\",\"13\":\"110\",\"14\":\"2bbl\",\"15\":\"3.15\",\"16\":\"3.58\",\"17\":\"9.10\",\"18\":\"100\",\"19\":\"5500\",\"20\":\"25\",\"21\":\"31\",\"22\":\"10345.00\"},{\"1\":\"std\",\"2\":\"four\",\"3\":\"sedan\",\"4\":\"rwd\",\"5\":\"front\",\"6\":\"94.3\",\"7\":\"170.7\",\"8\":\"61.8\",\"9\":\"53.5\",\"10\":\"2337\",\"11\":\"ohc\",\"12\":\"four\",\"13\":\"111\",\"14\":\"2bbl\",\"15\":\"3.31\",\"16\":\"3.23\",\"17\":\"8.50\",\"18\":\"78\",\"19\":\"4800\",\"20\":\"24\",\"21\":\"29\",\"22\":\"6785.00\"},{\"1\":\"std\",\"2\":\"two\",\"3\":\"sedan\",\"4\":\"fwd\",\"5\":\"front\",\"6\":\"94.5\",\"7\":\"155.9\",\"8\":\"63.6\",\"9\":\"52.0\",\"10\":\"1874\",\"11\":\"ohc\",\"12\":\"four\",\"13\":\"90\",\"14\":\"2bbl\",\"15\":\"3.03\",\"16\":\"3.11\",\"17\":\"9.60\",\"18\":\"70\",\"19\":\"5400\",\"20\":\"38\",\"21\":\"43\",\"22\":\"8916.50\"},{\"1\":\"std\",\"2\":\"four\",\"3\":\"sedan\",\"4\":\"fwd\",\"5\":\"front\",\"6\":\"94.5\",\"7\":\"155.9\",\"8\":\"63.6\",\"9\":\"52.0\",\"10\":\"1909\",\"11\":\"ohc\",\"12\":\"four\",\"13\":\"90\",\"14\":\"2bbl\",\"15\":\"3.03\",\"16\":\"3.11\",\"17\":\"9.60\",\"18\":\"70\",\"19\":\"5400\",\"20\":\"38\",\"21\":\"43\",\"22\":\"8916.50\"},{\"1\":\"std\",\"2\":\"two\",\"3\":\"hatchback\",\"4\":\"rwd\",\"5\":\"front\",\"6\":\"96.0\",\"7\":\"172.6\",\"8\":\"65.2\",\"9\":\"51.4\",\"10\":\"2734\",\"11\":\"ohc\",\"12\":\"four\",\"13\":\"119\",\"14\":\"spfi\",\"15\":\"3.43\",\"16\":\"3.23\",\"17\":\"9.20\",\"18\":\"90\",\"19\":\"5000\",\"20\":\"24\",\"21\":\"29\",\"22\":\"11048.00\"},{\"1\":\"std\",\"2\":\"four\",\"3\":\"sedan\",\"4\":\"rwd\",\"5\":\"front\",\"6\":\"113.0\",\"7\":\"199.6\",\"8\":\"69.6\",\"9\":\"52.8\",\"10\":\"4066\",\"11\":\"dohc\",\"12\":\"six\",\"13\":\"258\",\"14\":\"mpfi\",\"15\":\"3.63\",\"16\":\"4.17\",\"17\":\"8.10\",\"18\":\"176\",\"19\":\"4750\",\"20\":\"15\",\"21\":\"19\",\"22\":\"32250.00\"},{\"1\":\"std\",\"2\":\"four\",\"3\":\"sedan\",\"4\":\"rwd\",\"5\":\"front\",\"6\":\"113.0\",\"7\":\"199.6\",\"8\":\"69.6\",\"9\":\"52.8\",\"10\":\"4066\",\"11\":\"dohc\",\"12\":\"six\",\"13\":\"258\",\"14\":\"mpfi\",\"15\":\"3.63\",\"16\":\"4.17\",\"17\":\"8.10\",\"18\":\"176\",\"19\":\"4750\",\"20\":\"15\",\"21\":\"19\",\"22\":\"35550.00\"},{\"1\":\"std\",\"2\":\"two\",\"3\":\"sedan\",\"4\":\"rwd\",\"5\":\"front\",\"6\":\"102.0\",\"7\":\"191.7\",\"8\":\"70.6\",\"9\":\"47.8\",\"10\":\"3950\",\"11\":\"ohcv\",\"12\":\"twelve\",\"13\":\"326\",\"14\":\"mpfi\",\"15\":\"3.54\",\"16\":\"2.76\",\"17\":\"11.50\",\"18\":\"262\",\"19\":\"5000\",\"20\":\"13\",\"21\":\"17\",\"22\":\"36000.00\"},{\"1\":\"std\",\"2\":\"two\",\"3\":\"hatchback\",\"4\":\"fwd\",\"5\":\"front\",\"6\":\"93.1\",\"7\":\"159.1\",\"8\":\"64.2\",\"9\":\"54.1\",\"10\":\"1890\",\"11\":\"ohc\",\"12\":\"four\",\"13\":\"91\",\"14\":\"2bbl\",\"15\":\"3.03\",\"16\":\"3.15\",\"17\":\"9.00\",\"18\":\"68\",\"19\":\"5000\",\"20\":\"30\",\"21\":\"31\",\"22\":\"5195.00\"},{\"1\":\"std\",\"2\":\"two\",\"3\":\"hatchback\",\"4\":\"fwd\",\"5\":\"front\",\"6\":\"93.1\",\"7\":\"159.1\",\"8\":\"64.2\",\"9\":\"54.1\",\"10\":\"1900\",\"11\":\"ohc\",\"12\":\"four\",\"13\":\"91\",\"14\":\"2bbl\",\"15\":\"3.03\",\"16\":\"3.15\",\"17\":\"9.00\",\"18\":\"68\",\"19\":\"5000\",\"20\":\"31\",\"21\":\"38\",\"22\":\"6095.00\"},{\"1\":\"std\",\"2\":\"two\",\"3\":\"hatchback\",\"4\":\"fwd\",\"5\":\"front\",\"6\":\"93.1\",\"7\":\"159.1\",\"8\":\"64.2\",\"9\":\"54.1\",\"10\":\"1905\",\"11\":\"ohc\",\"12\":\"four\",\"13\":\"91\",\"14\":\"2bbl\",\"15\":\"3.03\",\"16\":\"3.15\",\"17\":\"9.00\",\"18\":\"68\",\"19\":\"5000\",\"20\":\"31\",\"21\":\"38\",\"22\":\"6795.00\"},{\"1\":\"std\",\"2\":\"four\",\"3\":\"sedan\",\"4\":\"fwd\",\"5\":\"front\",\"6\":\"93.1\",\"7\":\"166.8\",\"8\":\"64.2\",\"9\":\"54.1\",\"10\":\"1945\",\"11\":\"ohc\",\"12\":\"four\",\"13\":\"91\",\"14\":\"2bbl\",\"15\":\"3.03\",\"16\":\"3.15\",\"17\":\"9.00\",\"18\":\"68\",\"19\":\"5000\",\"20\":\"31\",\"21\":\"38\",\"22\":\"6695.00\"},{\"1\":\"std\",\"2\":\"four\",\"3\":\"sedan\",\"4\":\"fwd\",\"5\":\"front\",\"6\":\"93.1\",\"7\":\"166.8\",\"8\":\"64.2\",\"9\":\"54.1\",\"10\":\"1950\",\"11\":\"ohc\",\"12\":\"four\",\"13\":\"91\",\"14\":\"2bbl\",\"15\":\"3.08\",\"16\":\"3.15\",\"17\":\"9.00\",\"18\":\"68\",\"19\":\"5000\",\"20\":\"31\",\"21\":\"38\",\"22\":\"7395.00\"},{\"1\":\"std\",\"2\":\"two\",\"3\":\"hatchback\",\"4\":\"fwd\",\"5\":\"front\",\"6\":\"98.8\",\"7\":\"177.8\",\"8\":\"66.5\",\"9\":\"53.7\",\"10\":\"2385\",\"11\":\"ohc\",\"12\":\"four\",\"13\":\"122\",\"14\":\"2bbl\",\"15\":\"3.39\",\"16\":\"3.39\",\"17\":\"8.60\",\"18\":\"84\",\"19\":\"4800\",\"20\":\"26\",\"21\":\"32\",\"22\":\"8845.00\"},{\"1\":\"std\",\"2\":\"four\",\"3\":\"sedan\",\"4\":\"fwd\",\"5\":\"front\",\"6\":\"98.8\",\"7\":\"177.8\",\"8\":\"66.5\",\"9\":\"55.5\",\"10\":\"2410\",\"11\":\"ohc\",\"12\":\"four\",\"13\":\"122\",\"14\":\"2bbl\",\"15\":\"3.39\",\"16\":\"3.39\",\"17\":\"8.60\",\"18\":\"84\",\"19\":\"4800\",\"20\":\"26\",\"21\":\"32\",\"22\":\"8495.00\"},{\"1\":\"std\",\"2\":\"two\",\"3\":\"hatchback\",\"4\":\"fwd\",\"5\":\"front\",\"6\":\"98.8\",\"7\":\"177.8\",\"8\":\"66.5\",\"9\":\"53.7\",\"10\":\"2385\",\"11\":\"ohc\",\"12\":\"four\",\"13\":\"122\",\"14\":\"2bbl\",\"15\":\"3.39\",\"16\":\"3.39\",\"17\":\"8.60\",\"18\":\"84\",\"19\":\"4800\",\"20\":\"26\",\"21\":\"32\",\"22\":\"10595.00\"},{\"1\":\"std\",\"2\":\"four\",\"3\":\"sedan\",\"4\":\"fwd\",\"5\":\"front\",\"6\":\"98.8\",\"7\":\"177.8\",\"8\":\"66.5\",\"9\":\"55.5\",\"10\":\"2410\",\"11\":\"ohc\",\"12\":\"four\",\"13\":\"122\",\"14\":\"2bbl\",\"15\":\"3.39\",\"16\":\"3.39\",\"17\":\"8.60\",\"18\":\"84\",\"19\":\"4800\",\"20\":\"26\",\"21\":\"32\",\"22\":\"10245.00\"},{\"1\":\"std\",\"2\":\"four\",\"3\":\"hatchback\",\"4\":\"fwd\",\"5\":\"front\",\"6\":\"98.8\",\"7\":\"177.8\",\"8\":\"66.5\",\"9\":\"55.5\",\"10\":\"2425\",\"11\":\"ohc\",\"12\":\"four\",\"13\":\"122\",\"14\":\"2bbl\",\"15\":\"3.39\",\"16\":\"3.39\",\"17\":\"8.60\",\"18\":\"84\",\"19\":\"4800\",\"20\":\"26\",\"21\":\"32\",\"22\":\"11245.00\"},{\"1\":\"std\",\"2\":\"four\",\"3\":\"sedan\",\"4\":\"rwd\",\"5\":\"front\",\"6\":\"104.9\",\"7\":\"175.0\",\"8\":\"66.1\",\"9\":\"54.4\",\"10\":\"2670\",\"11\":\"ohc\",\"12\":\"four\",\"13\":\"140\",\"14\":\"mpfi\",\"15\":\"3.76\",\"16\":\"3.16\",\"17\":\"8.00\",\"18\":\"120\",\"19\":\"5000\",\"20\":\"19\",\"21\":\"27\",\"22\":\"18280.00\"},{\"1\":\"std\",\"2\":\"four\",\"3\":\"sedan\",\"4\":\"rwd\",\"5\":\"front\",\"6\":\"115.6\",\"7\":\"202.6\",\"8\":\"71.7\",\"9\":\"56.5\",\"10\":\"3740\",\"11\":\"ohcv\",\"12\":\"eight\",\"13\":\"234\",\"14\":\"mpfi\",\"15\":\"3.46\",\"16\":\"3.10\",\"17\":\"8.30\",\"18\":\"155\",\"19\":\"4750\",\"20\":\"16\",\"21\":\"18\",\"22\":\"34184.00\"},{\"1\":\"std\",\"2\":\"two\",\"3\":\"convertible\",\"4\":\"rwd\",\"5\":\"front\",\"6\":\"96.6\",\"7\":\"180.3\",\"8\":\"70.5\",\"9\":\"50.8\",\"10\":\"3685\",\"11\":\"ohcv\",\"12\":\"eight\",\"13\":\"234\",\"14\":\"mpfi\",\"15\":\"3.46\",\"16\":\"3.10\",\"17\":\"8.30\",\"18\":\"155\",\"19\":\"4750\",\"20\":\"16\",\"21\":\"18\",\"22\":\"35056.00\"},{\"1\":\"std\",\"2\":\"four\",\"3\":\"sedan\",\"4\":\"rwd\",\"5\":\"front\",\"6\":\"120.9\",\"7\":\"208.1\",\"8\":\"71.7\",\"9\":\"56.7\",\"10\":\"3900\",\"11\":\"ohcv\",\"12\":\"eight\",\"13\":\"308\",\"14\":\"mpfi\",\"15\":\"3.80\",\"16\":\"3.35\",\"17\":\"8.00\",\"18\":\"184\",\"19\":\"4500\",\"20\":\"14\",\"21\":\"16\",\"22\":\"40960.00\"},{\"1\":\"std\",\"2\":\"two\",\"3\":\"hardtop\",\"4\":\"rwd\",\"5\":\"front\",\"6\":\"112.0\",\"7\":\"199.2\",\"8\":\"72.0\",\"9\":\"55.4\",\"10\":\"3715\",\"11\":\"ohcv\",\"12\":\"eight\",\"13\":\"304\",\"14\":\"mpfi\",\"15\":\"3.80\",\"16\":\"3.35\",\"17\":\"8.00\",\"18\":\"184\",\"19\":\"4500\",\"20\":\"14\",\"21\":\"16\",\"22\":\"45400.00\"},{\"1\":\"turbo\",\"2\":\"two\",\"3\":\"hatchback\",\"4\":\"rwd\",\"5\":\"front\",\"6\":\"102.7\",\"7\":\"178.4\",\"8\":\"68.0\",\"9\":\"54.8\",\"10\":\"2910\",\"11\":\"ohc\",\"12\":\"four\",\"13\":\"140\",\"14\":\"mpfi\",\"15\":\"3.78\",\"16\":\"3.12\",\"17\":\"8.00\",\"18\":\"175\",\"19\":\"5000\",\"20\":\"19\",\"21\":\"24\",\"22\":\"16503.00\"},{\"1\":\"std\",\"2\":\"two\",\"3\":\"hatchback\",\"4\":\"fwd\",\"5\":\"front\",\"6\":\"93.7\",\"7\":\"157.3\",\"8\":\"64.4\",\"9\":\"50.8\",\"10\":\"1918\",\"11\":\"ohc\",\"12\":\"four\",\"13\":\"92\",\"14\":\"2bbl\",\"15\":\"2.97\",\"16\":\"3.23\",\"17\":\"9.40\",\"18\":\"68\",\"19\":\"5500\",\"20\":\"37\",\"21\":\"41\",\"22\":\"5389.00\"},{\"1\":\"std\",\"2\":\"two\",\"3\":\"hatchback\",\"4\":\"fwd\",\"5\":\"front\",\"6\":\"93.7\",\"7\":\"157.3\",\"8\":\"64.4\",\"9\":\"50.8\",\"10\":\"1944\",\"11\":\"ohc\",\"12\":\"four\",\"13\":\"92\",\"14\":\"2bbl\",\"15\":\"2.97\",\"16\":\"3.23\",\"17\":\"9.40\",\"18\":\"68\",\"19\":\"5500\",\"20\":\"31\",\"21\":\"38\",\"22\":\"6189.00\"},{\"1\":\"std\",\"2\":\"two\",\"3\":\"hatchback\",\"4\":\"fwd\",\"5\":\"front\",\"6\":\"93.7\",\"7\":\"157.3\",\"8\":\"64.4\",\"9\":\"50.8\",\"10\":\"2004\",\"11\":\"ohc\",\"12\":\"four\",\"13\":\"92\",\"14\":\"2bbl\",\"15\":\"2.97\",\"16\":\"3.23\",\"17\":\"9.40\",\"18\":\"68\",\"19\":\"5500\",\"20\":\"31\",\"21\":\"38\",\"22\":\"6669.00\"},{\"1\":\"turbo\",\"2\":\"two\",\"3\":\"hatchback\",\"4\":\"fwd\",\"5\":\"front\",\"6\":\"93.0\",\"7\":\"157.3\",\"8\":\"63.8\",\"9\":\"50.8\",\"10\":\"2145\",\"11\":\"ohc\",\"12\":\"four\",\"13\":\"98\",\"14\":\"spdi\",\"15\":\"3.03\",\"16\":\"3.39\",\"17\":\"7.60\",\"18\":\"102\",\"19\":\"5500\",\"20\":\"24\",\"21\":\"30\",\"22\":\"7689.00\"},{\"1\":\"turbo\",\"2\":\"two\",\"3\":\"hatchback\",\"4\":\"fwd\",\"5\":\"front\",\"6\":\"96.3\",\"7\":\"173.0\",\"8\":\"65.4\",\"9\":\"49.4\",\"10\":\"2370\",\"11\":\"ohc\",\"12\":\"four\",\"13\":\"110\",\"14\":\"spdi\",\"15\":\"3.17\",\"16\":\"3.46\",\"17\":\"7.50\",\"18\":\"116\",\"19\":\"5500\",\"20\":\"23\",\"21\":\"30\",\"22\":\"9959.00\"},{\"1\":\"std\",\"2\":\"two\",\"3\":\"hatchback\",\"4\":\"fwd\",\"5\":\"front\",\"6\":\"96.3\",\"7\":\"173.0\",\"8\":\"65.4\",\"9\":\"49.4\",\"10\":\"2328\",\"11\":\"ohc\",\"12\":\"four\",\"13\":\"122\",\"14\":\"2bbl\",\"15\":\"3.35\",\"16\":\"3.46\",\"17\":\"8.50\",\"18\":\"88\",\"19\":\"5000\",\"20\":\"25\",\"21\":\"32\",\"22\":\"8499.00\"},{\"1\":\"turbo\",\"2\":\"two\",\"3\":\"hatchback\",\"4\":\"fwd\",\"5\":\"front\",\"6\":\"95.9\",\"7\":\"173.2\",\"8\":\"66.3\",\"9\":\"50.2\",\"10\":\"2833\",\"11\":\"ohc\",\"12\":\"four\",\"13\":\"156\",\"14\":\"spdi\",\"15\":\"3.58\",\"16\":\"3.86\",\"17\":\"7.00\",\"18\":\"145\",\"19\":\"5000\",\"20\":\"19\",\"21\":\"24\",\"22\":\"12629.00\"},{\"1\":\"turbo\",\"2\":\"two\",\"3\":\"hatchback\",\"4\":\"fwd\",\"5\":\"front\",\"6\":\"95.9\",\"7\":\"173.2\",\"8\":\"66.3\",\"9\":\"50.2\",\"10\":\"2921\",\"11\":\"ohc\",\"12\":\"four\",\"13\":\"156\",\"14\":\"spdi\",\"15\":\"3.59\",\"16\":\"3.86\",\"17\":\"7.00\",\"18\":\"145\",\"19\":\"5000\",\"20\":\"19\",\"21\":\"24\",\"22\":\"14869.00\"},{\"1\":\"turbo\",\"2\":\"two\",\"3\":\"hatchback\",\"4\":\"fwd\",\"5\":\"front\",\"6\":\"95.9\",\"7\":\"173.2\",\"8\":\"66.3\",\"9\":\"50.2\",\"10\":\"2926\",\"11\":\"ohc\",\"12\":\"four\",\"13\":\"156\",\"14\":\"spdi\",\"15\":\"3.59\",\"16\":\"3.86\",\"17\":\"7.00\",\"18\":\"145\",\"19\":\"5000\",\"20\":\"19\",\"21\":\"24\",\"22\":\"14489.00\"},{\"1\":\"std\",\"2\":\"four\",\"3\":\"sedan\",\"4\":\"fwd\",\"5\":\"front\",\"6\":\"96.3\",\"7\":\"172.4\",\"8\":\"65.4\",\"9\":\"51.6\",\"10\":\"2365\",\"11\":\"ohc\",\"12\":\"four\",\"13\":\"122\",\"14\":\"2bbl\",\"15\":\"3.35\",\"16\":\"3.46\",\"17\":\"8.50\",\"18\":\"88\",\"19\":\"5000\",\"20\":\"25\",\"21\":\"32\",\"22\":\"6989.00\"},{\"1\":\"std\",\"2\":\"four\",\"3\":\"sedan\",\"4\":\"fwd\",\"5\":\"front\",\"6\":\"96.3\",\"7\":\"172.4\",\"8\":\"65.4\",\"9\":\"51.6\",\"10\":\"2405\",\"11\":\"ohc\",\"12\":\"four\",\"13\":\"122\",\"14\":\"2bbl\",\"15\":\"3.35\",\"16\":\"3.46\",\"17\":\"8.50\",\"18\":\"88\",\"19\":\"5000\",\"20\":\"25\",\"21\":\"32\",\"22\":\"8189.00\"},{\"1\":\"turbo\",\"2\":\"four\",\"3\":\"sedan\",\"4\":\"fwd\",\"5\":\"front\",\"6\":\"96.3\",\"7\":\"172.4\",\"8\":\"65.4\",\"9\":\"51.6\",\"10\":\"2403\",\"11\":\"ohc\",\"12\":\"four\",\"13\":\"110\",\"14\":\"spdi\",\"15\":\"3.17\",\"16\":\"3.46\",\"17\":\"7.50\",\"18\":\"116\",\"19\":\"5500\",\"20\":\"23\",\"21\":\"30\",\"22\":\"9279.00\"},{\"1\":\"std\",\"2\":\"four\",\"3\":\"sedan\",\"4\":\"fwd\",\"5\":\"front\",\"6\":\"96.3\",\"7\":\"172.4\",\"8\":\"65.4\",\"9\":\"51.6\",\"10\":\"2403\",\"11\":\"ohc\",\"12\":\"four\",\"13\":\"110\",\"14\":\"spdi\",\"15\":\"3.17\",\"16\":\"3.46\",\"17\":\"7.50\",\"18\":\"116\",\"19\":\"5500\",\"20\":\"23\",\"21\":\"30\",\"22\":\"9279.00\"},{\"1\":\"std\",\"2\":\"two\",\"3\":\"sedan\",\"4\":\"fwd\",\"5\":\"front\",\"6\":\"94.5\",\"7\":\"165.3\",\"8\":\"63.8\",\"9\":\"54.5\",\"10\":\"1889\",\"11\":\"ohc\",\"12\":\"four\",\"13\":\"97\",\"14\":\"2bbl\",\"15\":\"3.15\",\"16\":\"3.29\",\"17\":\"9.40\",\"18\":\"69\",\"19\":\"5200\",\"20\":\"31\",\"21\":\"37\",\"22\":\"5499.00\"},{\"1\":\"std\",\"2\":\"two\",\"3\":\"sedan\",\"4\":\"fwd\",\"5\":\"front\",\"6\":\"94.5\",\"7\":\"165.3\",\"8\":\"63.8\",\"9\":\"54.5\",\"10\":\"1918\",\"11\":\"ohc\",\"12\":\"four\",\"13\":\"97\",\"14\":\"2bbl\",\"15\":\"3.15\",\"16\":\"3.29\",\"17\":\"9.40\",\"18\":\"69\",\"19\":\"5200\",\"20\":\"31\",\"21\":\"37\",\"22\":\"6649.00\"},{\"1\":\"std\",\"2\":\"four\",\"3\":\"sedan\",\"4\":\"fwd\",\"5\":\"front\",\"6\":\"94.5\",\"7\":\"165.3\",\"8\":\"63.8\",\"9\":\"54.5\",\"10\":\"1938\",\"11\":\"ohc\",\"12\":\"four\",\"13\":\"97\",\"14\":\"2bbl\",\"15\":\"3.15\",\"16\":\"3.29\",\"17\":\"9.40\",\"18\":\"69\",\"19\":\"5200\",\"20\":\"31\",\"21\":\"37\",\"22\":\"6849.00\"},{\"1\":\"std\",\"2\":\"four\",\"3\":\"wagon\",\"4\":\"fwd\",\"5\":\"front\",\"6\":\"94.5\",\"7\":\"170.2\",\"8\":\"63.8\",\"9\":\"53.5\",\"10\":\"2024\",\"11\":\"ohc\",\"12\":\"four\",\"13\":\"97\",\"14\":\"2bbl\",\"15\":\"3.15\",\"16\":\"3.29\",\"17\":\"9.40\",\"18\":\"69\",\"19\":\"5200\",\"20\":\"31\",\"21\":\"37\",\"22\":\"7349.00\"},{\"1\":\"std\",\"2\":\"two\",\"3\":\"sedan\",\"4\":\"fwd\",\"5\":\"front\",\"6\":\"94.5\",\"7\":\"165.3\",\"8\":\"63.8\",\"9\":\"54.5\",\"10\":\"1951\",\"11\":\"ohc\",\"12\":\"four\",\"13\":\"97\",\"14\":\"2bbl\",\"15\":\"3.15\",\"16\":\"3.29\",\"17\":\"9.40\",\"18\":\"69\",\"19\":\"5200\",\"20\":\"31\",\"21\":\"37\",\"22\":\"7299.00\"},{\"1\":\"std\",\"2\":\"two\",\"3\":\"hatchback\",\"4\":\"fwd\",\"5\":\"front\",\"6\":\"94.5\",\"7\":\"165.6\",\"8\":\"63.8\",\"9\":\"53.3\",\"10\":\"2028\",\"11\":\"ohc\",\"12\":\"four\",\"13\":\"97\",\"14\":\"2bbl\",\"15\":\"3.15\",\"16\":\"3.29\",\"17\":\"9.40\",\"18\":\"69\",\"19\":\"5200\",\"20\":\"31\",\"21\":\"37\",\"22\":\"7799.00\"},{\"1\":\"std\",\"2\":\"four\",\"3\":\"sedan\",\"4\":\"fwd\",\"5\":\"front\",\"6\":\"94.5\",\"7\":\"165.3\",\"8\":\"63.8\",\"9\":\"54.5\",\"10\":\"1971\",\"11\":\"ohc\",\"12\":\"four\",\"13\":\"97\",\"14\":\"2bbl\",\"15\":\"3.15\",\"16\":\"3.29\",\"17\":\"9.40\",\"18\":\"69\",\"19\":\"5200\",\"20\":\"31\",\"21\":\"37\",\"22\":\"7499.00\"},{\"1\":\"std\",\"2\":\"four\",\"3\":\"wagon\",\"4\":\"fwd\",\"5\":\"front\",\"6\":\"94.5\",\"7\":\"170.2\",\"8\":\"63.8\",\"9\":\"53.5\",\"10\":\"2037\",\"11\":\"ohc\",\"12\":\"four\",\"13\":\"97\",\"14\":\"2bbl\",\"15\":\"3.15\",\"16\":\"3.29\",\"17\":\"9.40\",\"18\":\"69\",\"19\":\"5200\",\"20\":\"31\",\"21\":\"37\",\"22\":\"7999.00\"},{\"1\":\"std\",\"2\":\"two\",\"3\":\"hardtop\",\"4\":\"fwd\",\"5\":\"front\",\"6\":\"95.1\",\"7\":\"162.4\",\"8\":\"63.8\",\"9\":\"53.3\",\"10\":\"2008\",\"11\":\"ohc\",\"12\":\"four\",\"13\":\"97\",\"14\":\"2bbl\",\"15\":\"3.15\",\"16\":\"3.29\",\"17\":\"9.40\",\"18\":\"69\",\"19\":\"5200\",\"20\":\"31\",\"21\":\"37\",\"22\":\"8249.00\"},{\"1\":\"std\",\"2\":\"four\",\"3\":\"hatchback\",\"4\":\"fwd\",\"5\":\"front\",\"6\":\"97.2\",\"7\":\"173.4\",\"8\":\"65.2\",\"9\":\"54.7\",\"10\":\"2324\",\"11\":\"ohc\",\"12\":\"four\",\"13\":\"120\",\"14\":\"2bbl\",\"15\":\"3.33\",\"16\":\"3.47\",\"17\":\"8.50\",\"18\":\"97\",\"19\":\"5200\",\"20\":\"27\",\"21\":\"34\",\"22\":\"8949.00\"},{\"1\":\"std\",\"2\":\"four\",\"3\":\"sedan\",\"4\":\"fwd\",\"5\":\"front\",\"6\":\"97.2\",\"7\":\"173.4\",\"8\":\"65.2\",\"9\":\"54.7\",\"10\":\"2302\",\"11\":\"ohc\",\"12\":\"four\",\"13\":\"120\",\"14\":\"2bbl\",\"15\":\"3.33\",\"16\":\"3.47\",\"17\":\"8.50\",\"18\":\"97\",\"19\":\"5200\",\"20\":\"27\",\"21\":\"34\",\"22\":\"9549.00\"},{\"1\":\"std\",\"2\":\"four\",\"3\":\"sedan\",\"4\":\"fwd\",\"5\":\"front\",\"6\":\"100.4\",\"7\":\"181.7\",\"8\":\"66.5\",\"9\":\"55.1\",\"10\":\"3095\",\"11\":\"ohcv\",\"12\":\"six\",\"13\":\"181\",\"14\":\"mpfi\",\"15\":\"3.43\",\"16\":\"3.27\",\"17\":\"9.00\",\"18\":\"152\",\"19\":\"5200\",\"20\":\"17\",\"21\":\"22\",\"22\":\"13499.00\"},{\"1\":\"std\",\"2\":\"four\",\"3\":\"wagon\",\"4\":\"fwd\",\"5\":\"front\",\"6\":\"100.4\",\"7\":\"184.6\",\"8\":\"66.5\",\"9\":\"56.1\",\"10\":\"3296\",\"11\":\"ohcv\",\"12\":\"six\",\"13\":\"181\",\"14\":\"mpfi\",\"15\":\"3.43\",\"16\":\"3.27\",\"17\":\"9.00\",\"18\":\"152\",\"19\":\"5200\",\"20\":\"17\",\"21\":\"22\",\"22\":\"14399.00\"},{\"1\":\"std\",\"2\":\"four\",\"3\":\"sedan\",\"4\":\"fwd\",\"5\":\"front\",\"6\":\"100.4\",\"7\":\"184.6\",\"8\":\"66.5\",\"9\":\"55.1\",\"10\":\"3060\",\"11\":\"ohcv\",\"12\":\"six\",\"13\":\"181\",\"14\":\"mpfi\",\"15\":\"3.43\",\"16\":\"3.27\",\"17\":\"9.00\",\"18\":\"152\",\"19\":\"5200\",\"20\":\"19\",\"21\":\"25\",\"22\":\"13499.00\"},{\"1\":\"std\",\"2\":\"two\",\"3\":\"hatchback\",\"4\":\"rwd\",\"5\":\"front\",\"6\":\"91.3\",\"7\":\"170.7\",\"8\":\"67.9\",\"9\":\"49.7\",\"10\":\"3071\",\"11\":\"ohcv\",\"12\":\"six\",\"13\":\"181\",\"14\":\"mpfi\",\"15\":\"3.43\",\"16\":\"3.27\",\"17\":\"9.00\",\"18\":\"160\",\"19\":\"5200\",\"20\":\"19\",\"21\":\"25\",\"22\":\"17199.00\"},{\"1\":\"turbo\",\"2\":\"two\",\"3\":\"hatchback\",\"4\":\"rwd\",\"5\":\"front\",\"6\":\"91.3\",\"7\":\"170.7\",\"8\":\"67.9\",\"9\":\"49.7\",\"10\":\"3139\",\"11\":\"ohcv\",\"12\":\"six\",\"13\":\"181\",\"14\":\"mpfi\",\"15\":\"3.43\",\"16\":\"3.27\",\"17\":\"7.80\",\"18\":\"200\",\"19\":\"5200\",\"20\":\"17\",\"21\":\"23\",\"22\":\"19699.00\"},{\"1\":\"std\",\"2\":\"two\",\"3\":\"hatchback\",\"4\":\"rwd\",\"5\":\"front\",\"6\":\"99.2\",\"7\":\"178.5\",\"8\":\"67.9\",\"9\":\"49.7\",\"10\":\"3139\",\"11\":\"ohcv\",\"12\":\"six\",\"13\":\"181\",\"14\":\"mpfi\",\"15\":\"3.43\",\"16\":\"3.27\",\"17\":\"9.00\",\"18\":\"160\",\"19\":\"5200\",\"20\":\"19\",\"21\":\"25\",\"22\":\"18399.00\"},{\"1\":\"std\",\"2\":\"four\",\"3\":\"sedan\",\"4\":\"rwd\",\"5\":\"front\",\"6\":\"107.9\",\"7\":\"186.7\",\"8\":\"68.4\",\"9\":\"56.7\",\"10\":\"3020\",\"11\":\"l\",\"12\":\"four\",\"13\":\"120\",\"14\":\"mpfi\",\"15\":\"3.46\",\"16\":\"3.19\",\"17\":\"8.40\",\"18\":\"97\",\"19\":\"5000\",\"20\":\"19\",\"21\":\"24\",\"22\":\"11900.00\"},{\"1\":\"std\",\"2\":\"four\",\"3\":\"wagon\",\"4\":\"rwd\",\"5\":\"front\",\"6\":\"114.2\",\"7\":\"198.9\",\"8\":\"68.4\",\"9\":\"58.7\",\"10\":\"3230\",\"11\":\"l\",\"12\":\"four\",\"13\":\"120\",\"14\":\"mpfi\",\"15\":\"3.46\",\"16\":\"3.19\",\"17\":\"8.40\",\"18\":\"97\",\"19\":\"5000\",\"20\":\"19\",\"21\":\"24\",\"22\":\"12440.00\"},{\"1\":\"std\",\"2\":\"four\",\"3\":\"sedan\",\"4\":\"rwd\",\"5\":\"front\",\"6\":\"107.9\",\"7\":\"186.7\",\"8\":\"68.4\",\"9\":\"56.7\",\"10\":\"3075\",\"11\":\"l\",\"12\":\"four\",\"13\":\"120\",\"14\":\"mpfi\",\"15\":\"3.46\",\"16\":\"2.19\",\"17\":\"8.40\",\"18\":\"95\",\"19\":\"5000\",\"20\":\"19\",\"21\":\"24\",\"22\":\"15580.00\"},{\"1\":\"std\",\"2\":\"four\",\"3\":\"wagon\",\"4\":\"rwd\",\"5\":\"front\",\"6\":\"114.2\",\"7\":\"198.9\",\"8\":\"68.4\",\"9\":\"56.7\",\"10\":\"3285\",\"11\":\"l\",\"12\":\"four\",\"13\":\"120\",\"14\":\"mpfi\",\"15\":\"3.46\",\"16\":\"2.19\",\"17\":\"8.40\",\"18\":\"95\",\"19\":\"5000\",\"20\":\"19\",\"21\":\"24\",\"22\":\"16695.00\"},{\"1\":\"std\",\"2\":\"four\",\"3\":\"sedan\",\"4\":\"rwd\",\"5\":\"front\",\"6\":\"107.9\",\"7\":\"186.7\",\"8\":\"68.4\",\"9\":\"56.7\",\"10\":\"3075\",\"11\":\"l\",\"12\":\"four\",\"13\":\"120\",\"14\":\"mpfi\",\"15\":\"3.46\",\"16\":\"3.19\",\"17\":\"8.40\",\"18\":\"97\",\"19\":\"5000\",\"20\":\"19\",\"21\":\"24\",\"22\":\"16630.00\"},{\"1\":\"turbo\",\"2\":\"four\",\"3\":\"sedan\",\"4\":\"rwd\",\"5\":\"front\",\"6\":\"108.0\",\"7\":\"186.7\",\"8\":\"68.3\",\"9\":\"56.0\",\"10\":\"3130\",\"11\":\"l\",\"12\":\"four\",\"13\":\"134\",\"14\":\"mpfi\",\"15\":\"3.61\",\"16\":\"3.21\",\"17\":\"7.00\",\"18\":\"142\",\"19\":\"5600\",\"20\":\"18\",\"21\":\"24\",\"22\":\"18150.00\"},{\"1\":\"std\",\"2\":\"two\",\"3\":\"hatchback\",\"4\":\"fwd\",\"5\":\"front\",\"6\":\"93.7\",\"7\":\"157.3\",\"8\":\"63.8\",\"9\":\"50.8\",\"10\":\"1918\",\"11\":\"ohc\",\"12\":\"four\",\"13\":\"90\",\"14\":\"2bbl\",\"15\":\"2.97\",\"16\":\"3.23\",\"17\":\"9.40\",\"18\":\"68\",\"19\":\"5500\",\"20\":\"37\",\"21\":\"41\",\"22\":\"5572.00\"},{\"1\":\"turbo\",\"2\":\"two\",\"3\":\"hatchback\",\"4\":\"fwd\",\"5\":\"front\",\"6\":\"93.7\",\"7\":\"157.3\",\"8\":\"63.8\",\"9\":\"50.8\",\"10\":\"2128\",\"11\":\"ohc\",\"12\":\"four\",\"13\":\"98\",\"14\":\"spdi\",\"15\":\"3.03\",\"16\":\"3.39\",\"17\":\"7.60\",\"18\":\"102\",\"19\":\"5500\",\"20\":\"24\",\"21\":\"30\",\"22\":\"7957.00\"},{\"1\":\"std\",\"2\":\"four\",\"3\":\"hatchback\",\"4\":\"fwd\",\"5\":\"front\",\"6\":\"93.7\",\"7\":\"157.3\",\"8\":\"63.8\",\"9\":\"50.6\",\"10\":\"1967\",\"11\":\"ohc\",\"12\":\"four\",\"13\":\"90\",\"14\":\"2bbl\",\"15\":\"2.97\",\"16\":\"3.23\",\"17\":\"9.40\",\"18\":\"68\",\"19\":\"5500\",\"20\":\"31\",\"21\":\"38\",\"22\":\"6229.00\"},{\"1\":\"std\",\"2\":\"four\",\"3\":\"sedan\",\"4\":\"fwd\",\"5\":\"front\",\"6\":\"93.7\",\"7\":\"167.3\",\"8\":\"63.8\",\"9\":\"50.8\",\"10\":\"1989\",\"11\":\"ohc\",\"12\":\"four\",\"13\":\"90\",\"14\":\"2bbl\",\"15\":\"2.97\",\"16\":\"3.23\",\"17\":\"9.40\",\"18\":\"68\",\"19\":\"5500\",\"20\":\"31\",\"21\":\"38\",\"22\":\"6692.00\"},{\"1\":\"std\",\"2\":\"four\",\"3\":\"sedan\",\"4\":\"fwd\",\"5\":\"front\",\"6\":\"93.7\",\"7\":\"167.3\",\"8\":\"63.8\",\"9\":\"50.8\",\"10\":\"2191\",\"11\":\"ohc\",\"12\":\"four\",\"13\":\"98\",\"14\":\"2bbl\",\"15\":\"2.97\",\"16\":\"3.23\",\"17\":\"9.40\",\"18\":\"68\",\"19\":\"5500\",\"20\":\"31\",\"21\":\"38\",\"22\":\"7609.00\"},{\"1\":\"std\",\"2\":\"four\",\"3\":\"wagon\",\"4\":\"fwd\",\"5\":\"front\",\"6\":\"103.3\",\"7\":\"174.6\",\"8\":\"64.6\",\"9\":\"59.8\",\"10\":\"2535\",\"11\":\"ohc\",\"12\":\"four\",\"13\":\"122\",\"14\":\"2bbl\",\"15\":\"3.35\",\"16\":\"3.46\",\"17\":\"8.50\",\"18\":\"88\",\"19\":\"5000\",\"20\":\"24\",\"21\":\"30\",\"22\":\"8921.00\"},{\"1\":\"turbo\",\"2\":\"two\",\"3\":\"hatchback\",\"4\":\"rwd\",\"5\":\"front\",\"6\":\"95.9\",\"7\":\"173.2\",\"8\":\"66.3\",\"9\":\"50.2\",\"10\":\"2818\",\"11\":\"ohc\",\"12\":\"four\",\"13\":\"156\",\"14\":\"spdi\",\"15\":\"3.59\",\"16\":\"3.86\",\"17\":\"7.00\",\"18\":\"145\",\"19\":\"5000\",\"20\":\"19\",\"21\":\"24\",\"22\":\"12764.00\"},{\"1\":\"std\",\"2\":\"two\",\"3\":\"hatchback\",\"4\":\"rwd\",\"5\":\"front\",\"6\":\"94.5\",\"7\":\"168.9\",\"8\":\"68.3\",\"9\":\"50.2\",\"10\":\"2778\",\"11\":\"ohc\",\"12\":\"four\",\"13\":\"151\",\"14\":\"mpfi\",\"15\":\"3.94\",\"16\":\"3.11\",\"17\":\"9.50\",\"18\":\"143\",\"19\":\"5500\",\"20\":\"19\",\"21\":\"27\",\"22\":\"22018.00\"},{\"1\":\"std\",\"2\":\"two\",\"3\":\"hardtop\",\"4\":\"rwd\",\"5\":\"rear\",\"6\":\"89.5\",\"7\":\"168.9\",\"8\":\"65.0\",\"9\":\"51.6\",\"10\":\"2756\",\"11\":\"ohcf\",\"12\":\"six\",\"13\":\"194\",\"14\":\"mpfi\",\"15\":\"3.74\",\"16\":\"2.90\",\"17\":\"9.50\",\"18\":\"207\",\"19\":\"5900\",\"20\":\"17\",\"21\":\"25\",\"22\":\"32528.00\"},{\"1\":\"std\",\"2\":\"two\",\"3\":\"hardtop\",\"4\":\"rwd\",\"5\":\"rear\",\"6\":\"89.5\",\"7\":\"168.9\",\"8\":\"65.0\",\"9\":\"51.6\",\"10\":\"2756\",\"11\":\"ohcf\",\"12\":\"six\",\"13\":\"194\",\"14\":\"mpfi\",\"15\":\"3.74\",\"16\":\"2.90\",\"17\":\"9.50\",\"18\":\"207\",\"19\":\"5900\",\"20\":\"17\",\"21\":\"25\",\"22\":\"34028.00\"},{\"1\":\"std\",\"2\":\"two\",\"3\":\"convertible\",\"4\":\"rwd\",\"5\":\"rear\",\"6\":\"89.5\",\"7\":\"168.9\",\"8\":\"65.0\",\"9\":\"51.6\",\"10\":\"2800\",\"11\":\"ohcf\",\"12\":\"six\",\"13\":\"194\",\"14\":\"mpfi\",\"15\":\"3.74\",\"16\":\"2.90\",\"17\":\"9.50\",\"18\":\"207\",\"19\":\"5900\",\"20\":\"17\",\"21\":\"25\",\"22\":\"37028.00\"},{\"1\":\"std\",\"2\":\"two\",\"3\":\"hatchback\",\"4\":\"rwd\",\"5\":\"front\",\"6\":\"98.4\",\"7\":\"175.7\",\"8\":\"72.3\",\"9\":\"50.5\",\"10\":\"3366\",\"11\":\"dohcv\",\"12\":\"eight\",\"13\":\"203\",\"14\":\"mpfi\",\"15\":\"3.94\",\"16\":\"3.11\",\"17\":\"10.00\",\"18\":\"288\",\"19\":\"5750\",\"20\":\"17\",\"21\":\"28\",\"22\":\"31400.50\"},{\"1\":\"std\",\"2\":\"four\",\"3\":\"wagon\",\"4\":\"fwd\",\"5\":\"front\",\"6\":\"96.1\",\"7\":\"181.5\",\"8\":\"66.5\",\"9\":\"55.2\",\"10\":\"2579\",\"11\":\"ohc\",\"12\":\"four\",\"13\":\"132\",\"14\":\"mpfi\",\"15\":\"3.46\",\"16\":\"3.90\",\"17\":\"8.70\",\"18\":\"90\",\"19\":\"5100\",\"20\":\"23\",\"21\":\"31\",\"22\":\"9295.00\"},{\"1\":\"std\",\"2\":\"two\",\"3\":\"hatchback\",\"4\":\"fwd\",\"5\":\"front\",\"6\":\"96.1\",\"7\":\"176.8\",\"8\":\"66.6\",\"9\":\"50.5\",\"10\":\"2460\",\"11\":\"ohc\",\"12\":\"four\",\"13\":\"132\",\"14\":\"mpfi\",\"15\":\"3.46\",\"16\":\"3.90\",\"17\":\"8.70\",\"18\":\"90\",\"19\":\"5100\",\"20\":\"23\",\"21\":\"31\",\"22\":\"9895.00\"},{\"1\":\"std\",\"2\":\"two\",\"3\":\"hatchback\",\"4\":\"fwd\",\"5\":\"front\",\"6\":\"99.1\",\"7\":\"186.6\",\"8\":\"66.5\",\"9\":\"56.1\",\"10\":\"2658\",\"11\":\"ohc\",\"12\":\"four\",\"13\":\"121\",\"14\":\"mpfi\",\"15\":\"3.54\",\"16\":\"3.07\",\"17\":\"9.31\",\"18\":\"110\",\"19\":\"5250\",\"20\":\"21\",\"21\":\"28\",\"22\":\"11850.00\"},{\"1\":\"std\",\"2\":\"four\",\"3\":\"sedan\",\"4\":\"fwd\",\"5\":\"front\",\"6\":\"99.1\",\"7\":\"186.6\",\"8\":\"66.5\",\"9\":\"56.1\",\"10\":\"2695\",\"11\":\"ohc\",\"12\":\"four\",\"13\":\"121\",\"14\":\"mpfi\",\"15\":\"3.54\",\"16\":\"3.07\",\"17\":\"9.30\",\"18\":\"110\",\"19\":\"5250\",\"20\":\"21\",\"21\":\"28\",\"22\":\"12170.00\"},{\"1\":\"std\",\"2\":\"two\",\"3\":\"hatchback\",\"4\":\"fwd\",\"5\":\"front\",\"6\":\"99.1\",\"7\":\"186.6\",\"8\":\"66.5\",\"9\":\"56.1\",\"10\":\"2707\",\"11\":\"ohc\",\"12\":\"four\",\"13\":\"121\",\"14\":\"mpfi\",\"15\":\"2.54\",\"16\":\"2.07\",\"17\":\"9.30\",\"18\":\"110\",\"19\":\"5250\",\"20\":\"21\",\"21\":\"28\",\"22\":\"15040.00\"},{\"1\":\"std\",\"2\":\"four\",\"3\":\"sedan\",\"4\":\"fwd\",\"5\":\"front\",\"6\":\"99.1\",\"7\":\"186.6\",\"8\":\"66.5\",\"9\":\"56.1\",\"10\":\"2758\",\"11\":\"ohc\",\"12\":\"four\",\"13\":\"121\",\"14\":\"mpfi\",\"15\":\"3.54\",\"16\":\"3.07\",\"17\":\"9.30\",\"18\":\"110\",\"19\":\"5250\",\"20\":\"21\",\"21\":\"28\",\"22\":\"15510.00\"},{\"1\":\"turbo\",\"2\":\"two\",\"3\":\"hatchback\",\"4\":\"fwd\",\"5\":\"front\",\"6\":\"99.1\",\"7\":\"186.6\",\"8\":\"66.5\",\"9\":\"56.1\",\"10\":\"2808\",\"11\":\"dohc\",\"12\":\"four\",\"13\":\"121\",\"14\":\"mpfi\",\"15\":\"3.54\",\"16\":\"3.07\",\"17\":\"9.00\",\"18\":\"160\",\"19\":\"5500\",\"20\":\"19\",\"21\":\"26\",\"22\":\"18150.00\"},{\"1\":\"turbo\",\"2\":\"four\",\"3\":\"sedan\",\"4\":\"fwd\",\"5\":\"front\",\"6\":\"99.1\",\"7\":\"186.6\",\"8\":\"66.5\",\"9\":\"56.1\",\"10\":\"2847\",\"11\":\"dohc\",\"12\":\"four\",\"13\":\"121\",\"14\":\"mpfi\",\"15\":\"3.54\",\"16\":\"3.07\",\"17\":\"9.00\",\"18\":\"160\",\"19\":\"5500\",\"20\":\"19\",\"21\":\"26\",\"22\":\"18620.00\"},{\"1\":\"std\",\"2\":\"two\",\"3\":\"hatchback\",\"4\":\"fwd\",\"5\":\"front\",\"6\":\"93.7\",\"7\":\"156.9\",\"8\":\"63.4\",\"9\":\"53.7\",\"10\":\"2050\",\"11\":\"ohcf\",\"12\":\"four\",\"13\":\"97\",\"14\":\"2bbl\",\"15\":\"3.62\",\"16\":\"2.36\",\"17\":\"9.00\",\"18\":\"69\",\"19\":\"4900\",\"20\":\"31\",\"21\":\"36\",\"22\":\"5118.00\"},{\"1\":\"std\",\"2\":\"two\",\"3\":\"hatchback\",\"4\":\"fwd\",\"5\":\"front\",\"6\":\"93.7\",\"7\":\"157.9\",\"8\":\"63.6\",\"9\":\"53.7\",\"10\":\"2120\",\"11\":\"ohcf\",\"12\":\"four\",\"13\":\"108\",\"14\":\"2bbl\",\"15\":\"3.62\",\"16\":\"2.64\",\"17\":\"8.70\",\"18\":\"73\",\"19\":\"4400\",\"20\":\"26\",\"21\":\"31\",\"22\":\"7053.00\"},{\"1\":\"std\",\"2\":\"two\",\"3\":\"hatchback\",\"4\":\"4wd\",\"5\":\"front\",\"6\":\"93.3\",\"7\":\"157.3\",\"8\":\"63.8\",\"9\":\"55.7\",\"10\":\"2240\",\"11\":\"ohcf\",\"12\":\"four\",\"13\":\"108\",\"14\":\"2bbl\",\"15\":\"3.62\",\"16\":\"2.64\",\"17\":\"8.70\",\"18\":\"73\",\"19\":\"4400\",\"20\":\"26\",\"21\":\"31\",\"22\":\"7603.00\"},{\"1\":\"std\",\"2\":\"four\",\"3\":\"sedan\",\"4\":\"fwd\",\"5\":\"front\",\"6\":\"97.2\",\"7\":\"172.0\",\"8\":\"65.4\",\"9\":\"52.5\",\"10\":\"2145\",\"11\":\"ohcf\",\"12\":\"four\",\"13\":\"108\",\"14\":\"2bbl\",\"15\":\"3.62\",\"16\":\"2.64\",\"17\":\"9.50\",\"18\":\"82\",\"19\":\"4800\",\"20\":\"32\",\"21\":\"37\",\"22\":\"7126.00\"},{\"1\":\"std\",\"2\":\"four\",\"3\":\"sedan\",\"4\":\"fwd\",\"5\":\"front\",\"6\":\"97.2\",\"7\":\"172.0\",\"8\":\"65.4\",\"9\":\"52.5\",\"10\":\"2190\",\"11\":\"ohcf\",\"12\":\"four\",\"13\":\"108\",\"14\":\"2bbl\",\"15\":\"3.62\",\"16\":\"2.64\",\"17\":\"9.50\",\"18\":\"82\",\"19\":\"4400\",\"20\":\"28\",\"21\":\"33\",\"22\":\"7775.00\"},{\"1\":\"std\",\"2\":\"four\",\"3\":\"sedan\",\"4\":\"fwd\",\"5\":\"front\",\"6\":\"97.2\",\"7\":\"172.0\",\"8\":\"65.4\",\"9\":\"52.5\",\"10\":\"2340\",\"11\":\"ohcf\",\"12\":\"four\",\"13\":\"108\",\"14\":\"mpfi\",\"15\":\"3.62\",\"16\":\"2.64\",\"17\":\"9.00\",\"18\":\"94\",\"19\":\"5200\",\"20\":\"26\",\"21\":\"32\",\"22\":\"9960.00\"},{\"1\":\"std\",\"2\":\"four\",\"3\":\"sedan\",\"4\":\"4wd\",\"5\":\"front\",\"6\":\"97.0\",\"7\":\"172.0\",\"8\":\"65.4\",\"9\":\"54.3\",\"10\":\"2385\",\"11\":\"ohcf\",\"12\":\"four\",\"13\":\"108\",\"14\":\"2bbl\",\"15\":\"3.62\",\"16\":\"2.64\",\"17\":\"9.00\",\"18\":\"82\",\"19\":\"4800\",\"20\":\"24\",\"21\":\"25\",\"22\":\"9233.00\"},{\"1\":\"turbo\",\"2\":\"four\",\"3\":\"sedan\",\"4\":\"4wd\",\"5\":\"front\",\"6\":\"97.0\",\"7\":\"172.0\",\"8\":\"65.4\",\"9\":\"54.3\",\"10\":\"2510\",\"11\":\"ohcf\",\"12\":\"four\",\"13\":\"108\",\"14\":\"mpfi\",\"15\":\"3.62\",\"16\":\"2.64\",\"17\":\"7.70\",\"18\":\"111\",\"19\":\"4800\",\"20\":\"24\",\"21\":\"29\",\"22\":\"11259.00\"},{\"1\":\"std\",\"2\":\"four\",\"3\":\"wagon\",\"4\":\"fwd\",\"5\":\"front\",\"6\":\"97.0\",\"7\":\"173.5\",\"8\":\"65.4\",\"9\":\"53.0\",\"10\":\"2290\",\"11\":\"ohcf\",\"12\":\"four\",\"13\":\"108\",\"14\":\"2bbl\",\"15\":\"3.62\",\"16\":\"2.64\",\"17\":\"9.00\",\"18\":\"82\",\"19\":\"4800\",\"20\":\"28\",\"21\":\"32\",\"22\":\"7463.00\"},{\"1\":\"std\",\"2\":\"four\",\"3\":\"wagon\",\"4\":\"fwd\",\"5\":\"front\",\"6\":\"97.0\",\"7\":\"173.5\",\"8\":\"65.4\",\"9\":\"53.0\",\"10\":\"2455\",\"11\":\"ohcf\",\"12\":\"four\",\"13\":\"108\",\"14\":\"mpfi\",\"15\":\"3.62\",\"16\":\"2.64\",\"17\":\"9.00\",\"18\":\"94\",\"19\":\"5200\",\"20\":\"25\",\"21\":\"31\",\"22\":\"10198.00\"},{\"1\":\"std\",\"2\":\"four\",\"3\":\"wagon\",\"4\":\"4wd\",\"5\":\"front\",\"6\":\"96.9\",\"7\":\"173.6\",\"8\":\"65.4\",\"9\":\"54.9\",\"10\":\"2420\",\"11\":\"ohcf\",\"12\":\"four\",\"13\":\"108\",\"14\":\"2bbl\",\"15\":\"3.62\",\"16\":\"2.64\",\"17\":\"9.00\",\"18\":\"82\",\"19\":\"4800\",\"20\":\"23\",\"21\":\"29\",\"22\":\"8013.00\"},{\"1\":\"turbo\",\"2\":\"four\",\"3\":\"wagon\",\"4\":\"4wd\",\"5\":\"front\",\"6\":\"96.9\",\"7\":\"173.6\",\"8\":\"65.4\",\"9\":\"54.9\",\"10\":\"2650\",\"11\":\"ohcf\",\"12\":\"four\",\"13\":\"108\",\"14\":\"mpfi\",\"15\":\"3.62\",\"16\":\"2.64\",\"17\":\"7.70\",\"18\":\"111\",\"19\":\"4800\",\"20\":\"23\",\"21\":\"23\",\"22\":\"11694.00\"},{\"1\":\"std\",\"2\":\"two\",\"3\":\"hatchback\",\"4\":\"fwd\",\"5\":\"front\",\"6\":\"95.7\",\"7\":\"158.7\",\"8\":\"63.6\",\"9\":\"54.5\",\"10\":\"1985\",\"11\":\"ohc\",\"12\":\"four\",\"13\":\"92\",\"14\":\"2bbl\",\"15\":\"3.05\",\"16\":\"3.03\",\"17\":\"9.00\",\"18\":\"62\",\"19\":\"4800\",\"20\":\"35\",\"21\":\"39\",\"22\":\"5348.00\"},{\"1\":\"std\",\"2\":\"two\",\"3\":\"hatchback\",\"4\":\"fwd\",\"5\":\"front\",\"6\":\"95.7\",\"7\":\"158.7\",\"8\":\"63.6\",\"9\":\"54.5\",\"10\":\"2040\",\"11\":\"ohc\",\"12\":\"four\",\"13\":\"92\",\"14\":\"2bbl\",\"15\":\"3.05\",\"16\":\"3.03\",\"17\":\"9.00\",\"18\":\"62\",\"19\":\"4800\",\"20\":\"31\",\"21\":\"38\",\"22\":\"6338.00\"},{\"1\":\"std\",\"2\":\"four\",\"3\":\"hatchback\",\"4\":\"fwd\",\"5\":\"front\",\"6\":\"95.7\",\"7\":\"158.7\",\"8\":\"63.6\",\"9\":\"54.5\",\"10\":\"2015\",\"11\":\"ohc\",\"12\":\"four\",\"13\":\"92\",\"14\":\"2bbl\",\"15\":\"3.05\",\"16\":\"3.03\",\"17\":\"9.00\",\"18\":\"62\",\"19\":\"4800\",\"20\":\"31\",\"21\":\"38\",\"22\":\"6488.00\"},{\"1\":\"std\",\"2\":\"four\",\"3\":\"wagon\",\"4\":\"fwd\",\"5\":\"front\",\"6\":\"95.7\",\"7\":\"169.7\",\"8\":\"63.6\",\"9\":\"59.1\",\"10\":\"2280\",\"11\":\"ohc\",\"12\":\"four\",\"13\":\"92\",\"14\":\"2bbl\",\"15\":\"3.05\",\"16\":\"3.03\",\"17\":\"9.00\",\"18\":\"62\",\"19\":\"4800\",\"20\":\"31\",\"21\":\"37\",\"22\":\"6918.00\"},{\"1\":\"std\",\"2\":\"four\",\"3\":\"wagon\",\"4\":\"4wd\",\"5\":\"front\",\"6\":\"95.7\",\"7\":\"169.7\",\"8\":\"63.6\",\"9\":\"59.1\",\"10\":\"2290\",\"11\":\"ohc\",\"12\":\"four\",\"13\":\"92\",\"14\":\"2bbl\",\"15\":\"3.05\",\"16\":\"3.03\",\"17\":\"9.00\",\"18\":\"62\",\"19\":\"4800\",\"20\":\"27\",\"21\":\"32\",\"22\":\"7898.00\"},{\"1\":\"std\",\"2\":\"four\",\"3\":\"wagon\",\"4\":\"4wd\",\"5\":\"front\",\"6\":\"95.7\",\"7\":\"169.7\",\"8\":\"63.6\",\"9\":\"59.1\",\"10\":\"3110\",\"11\":\"ohc\",\"12\":\"four\",\"13\":\"92\",\"14\":\"2bbl\",\"15\":\"3.05\",\"16\":\"3.03\",\"17\":\"9.00\",\"18\":\"62\",\"19\":\"4800\",\"20\":\"27\",\"21\":\"32\",\"22\":\"8778.00\"},{\"1\":\"std\",\"2\":\"four\",\"3\":\"sedan\",\"4\":\"fwd\",\"5\":\"front\",\"6\":\"95.7\",\"7\":\"166.3\",\"8\":\"64.4\",\"9\":\"53.0\",\"10\":\"2081\",\"11\":\"ohc\",\"12\":\"four\",\"13\":\"98\",\"14\":\"2bbl\",\"15\":\"3.19\",\"16\":\"3.03\",\"17\":\"9.00\",\"18\":\"70\",\"19\":\"4800\",\"20\":\"30\",\"21\":\"37\",\"22\":\"6938.00\"},{\"1\":\"std\",\"2\":\"four\",\"3\":\"hatchback\",\"4\":\"fwd\",\"5\":\"front\",\"6\":\"95.7\",\"7\":\"166.3\",\"8\":\"64.4\",\"9\":\"52.8\",\"10\":\"2109\",\"11\":\"ohc\",\"12\":\"four\",\"13\":\"98\",\"14\":\"2bbl\",\"15\":\"3.19\",\"16\":\"3.03\",\"17\":\"9.00\",\"18\":\"70\",\"19\":\"4800\",\"20\":\"30\",\"21\":\"37\",\"22\":\"7198.00\"},{\"1\":\"std\",\"2\":\"four\",\"3\":\"sedan\",\"4\":\"fwd\",\"5\":\"front\",\"6\":\"95.7\",\"7\":\"166.3\",\"8\":\"64.4\",\"9\":\"53.0\",\"10\":\"2094\",\"11\":\"ohc\",\"12\":\"four\",\"13\":\"98\",\"14\":\"2bbl\",\"15\":\"3.19\",\"16\":\"3.03\",\"17\":\"9.00\",\"18\":\"70\",\"19\":\"4800\",\"20\":\"38\",\"21\":\"47\",\"22\":\"7738.00\"},{\"1\":\"std\",\"2\":\"four\",\"3\":\"hatchback\",\"4\":\"fwd\",\"5\":\"front\",\"6\":\"95.7\",\"7\":\"166.3\",\"8\":\"64.4\",\"9\":\"52.8\",\"10\":\"2122\",\"11\":\"ohc\",\"12\":\"four\",\"13\":\"98\",\"14\":\"2bbl\",\"15\":\"3.19\",\"16\":\"3.03\",\"17\":\"9.00\",\"18\":\"70\",\"19\":\"4800\",\"20\":\"28\",\"21\":\"34\",\"22\":\"8358.00\"},{\"1\":\"std\",\"2\":\"four\",\"3\":\"sedan\",\"4\":\"fwd\",\"5\":\"front\",\"6\":\"95.7\",\"7\":\"166.3\",\"8\":\"64.4\",\"9\":\"52.8\",\"10\":\"2140\",\"11\":\"ohc\",\"12\":\"four\",\"13\":\"98\",\"14\":\"2bbl\",\"15\":\"3.19\",\"16\":\"3.03\",\"17\":\"9.00\",\"18\":\"70\",\"19\":\"4800\",\"20\":\"28\",\"21\":\"34\",\"22\":\"9258.00\"},{\"1\":\"std\",\"2\":\"two\",\"3\":\"sedan\",\"4\":\"rwd\",\"5\":\"front\",\"6\":\"94.5\",\"7\":\"168.7\",\"8\":\"64.0\",\"9\":\"52.6\",\"10\":\"2169\",\"11\":\"ohc\",\"12\":\"four\",\"13\":\"98\",\"14\":\"2bbl\",\"15\":\"3.19\",\"16\":\"3.03\",\"17\":\"9.00\",\"18\":\"70\",\"19\":\"4800\",\"20\":\"29\",\"21\":\"34\",\"22\":\"8058.00\"},{\"1\":\"std\",\"2\":\"two\",\"3\":\"hatchback\",\"4\":\"rwd\",\"5\":\"front\",\"6\":\"94.5\",\"7\":\"168.7\",\"8\":\"64.0\",\"9\":\"52.6\",\"10\":\"2204\",\"11\":\"ohc\",\"12\":\"four\",\"13\":\"98\",\"14\":\"2bbl\",\"15\":\"3.19\",\"16\":\"3.03\",\"17\":\"9.00\",\"18\":\"70\",\"19\":\"4800\",\"20\":\"29\",\"21\":\"34\",\"22\":\"8238.00\"},{\"1\":\"std\",\"2\":\"two\",\"3\":\"sedan\",\"4\":\"rwd\",\"5\":\"front\",\"6\":\"94.5\",\"7\":\"168.7\",\"8\":\"64.0\",\"9\":\"52.6\",\"10\":\"2265\",\"11\":\"dohc\",\"12\":\"four\",\"13\":\"98\",\"14\":\"mpfi\",\"15\":\"3.24\",\"16\":\"3.08\",\"17\":\"9.40\",\"18\":\"112\",\"19\":\"6600\",\"20\":\"26\",\"21\":\"29\",\"22\":\"9298.00\"},{\"1\":\"std\",\"2\":\"two\",\"3\":\"hatchback\",\"4\":\"rwd\",\"5\":\"front\",\"6\":\"94.5\",\"7\":\"168.7\",\"8\":\"64.0\",\"9\":\"52.6\",\"10\":\"2300\",\"11\":\"dohc\",\"12\":\"four\",\"13\":\"98\",\"14\":\"mpfi\",\"15\":\"3.24\",\"16\":\"3.08\",\"17\":\"9.40\",\"18\":\"112\",\"19\":\"6600\",\"20\":\"26\",\"21\":\"29\",\"22\":\"9538.00\"},{\"1\":\"std\",\"2\":\"two\",\"3\":\"hardtop\",\"4\":\"rwd\",\"5\":\"front\",\"6\":\"98.4\",\"7\":\"176.2\",\"8\":\"65.6\",\"9\":\"52.0\",\"10\":\"2540\",\"11\":\"ohc\",\"12\":\"four\",\"13\":\"146\",\"14\":\"mpfi\",\"15\":\"3.62\",\"16\":\"3.50\",\"17\":\"9.30\",\"18\":\"116\",\"19\":\"4800\",\"20\":\"24\",\"21\":\"30\",\"22\":\"8449.00\"},{\"1\":\"std\",\"2\":\"two\",\"3\":\"hardtop\",\"4\":\"rwd\",\"5\":\"front\",\"6\":\"98.4\",\"7\":\"176.2\",\"8\":\"65.6\",\"9\":\"52.0\",\"10\":\"2536\",\"11\":\"ohc\",\"12\":\"four\",\"13\":\"146\",\"14\":\"mpfi\",\"15\":\"3.62\",\"16\":\"3.50\",\"17\":\"9.30\",\"18\":\"116\",\"19\":\"4800\",\"20\":\"24\",\"21\":\"30\",\"22\":\"9639.00\"},{\"1\":\"std\",\"2\":\"two\",\"3\":\"hatchback\",\"4\":\"rwd\",\"5\":\"front\",\"6\":\"98.4\",\"7\":\"176.2\",\"8\":\"65.6\",\"9\":\"52.0\",\"10\":\"2551\",\"11\":\"ohc\",\"12\":\"four\",\"13\":\"146\",\"14\":\"mpfi\",\"15\":\"3.62\",\"16\":\"3.50\",\"17\":\"9.30\",\"18\":\"116\",\"19\":\"4800\",\"20\":\"24\",\"21\":\"30\",\"22\":\"9989.00\"},{\"1\":\"std\",\"2\":\"two\",\"3\":\"hardtop\",\"4\":\"rwd\",\"5\":\"front\",\"6\":\"98.4\",\"7\":\"176.2\",\"8\":\"65.6\",\"9\":\"52.0\",\"10\":\"2679\",\"11\":\"ohc\",\"12\":\"four\",\"13\":\"146\",\"14\":\"mpfi\",\"15\":\"3.62\",\"16\":\"3.50\",\"17\":\"9.30\",\"18\":\"116\",\"19\":\"4800\",\"20\":\"24\",\"21\":\"30\",\"22\":\"11199.00\"},{\"1\":\"std\",\"2\":\"two\",\"3\":\"hatchback\",\"4\":\"rwd\",\"5\":\"front\",\"6\":\"98.4\",\"7\":\"176.2\",\"8\":\"65.6\",\"9\":\"52.0\",\"10\":\"2714\",\"11\":\"ohc\",\"12\":\"four\",\"13\":\"146\",\"14\":\"mpfi\",\"15\":\"3.62\",\"16\":\"3.50\",\"17\":\"9.30\",\"18\":\"116\",\"19\":\"4800\",\"20\":\"24\",\"21\":\"30\",\"22\":\"11549.00\"},{\"1\":\"std\",\"2\":\"two\",\"3\":\"convertible\",\"4\":\"rwd\",\"5\":\"front\",\"6\":\"98.4\",\"7\":\"176.2\",\"8\":\"65.6\",\"9\":\"53.0\",\"10\":\"2975\",\"11\":\"ohc\",\"12\":\"four\",\"13\":\"146\",\"14\":\"mpfi\",\"15\":\"3.62\",\"16\":\"3.50\",\"17\":\"9.30\",\"18\":\"116\",\"19\":\"4800\",\"20\":\"24\",\"21\":\"30\",\"22\":\"17669.00\"},{\"1\":\"std\",\"2\":\"four\",\"3\":\"sedan\",\"4\":\"fwd\",\"5\":\"front\",\"6\":\"102.4\",\"7\":\"175.6\",\"8\":\"66.5\",\"9\":\"54.9\",\"10\":\"2326\",\"11\":\"ohc\",\"12\":\"four\",\"13\":\"122\",\"14\":\"mpfi\",\"15\":\"3.31\",\"16\":\"3.54\",\"17\":\"8.70\",\"18\":\"92\",\"19\":\"4200\",\"20\":\"29\",\"21\":\"34\",\"22\":\"8948.00\"},{\"1\":\"std\",\"2\":\"four\",\"3\":\"hatchback\",\"4\":\"fwd\",\"5\":\"front\",\"6\":\"102.4\",\"7\":\"175.6\",\"8\":\"66.5\",\"9\":\"53.9\",\"10\":\"2414\",\"11\":\"ohc\",\"12\":\"four\",\"13\":\"122\",\"14\":\"mpfi\",\"15\":\"3.31\",\"16\":\"3.54\",\"17\":\"8.70\",\"18\":\"92\",\"19\":\"4200\",\"20\":\"27\",\"21\":\"32\",\"22\":\"9988.00\"},{\"1\":\"std\",\"2\":\"four\",\"3\":\"sedan\",\"4\":\"fwd\",\"5\":\"front\",\"6\":\"102.4\",\"7\":\"175.6\",\"8\":\"66.5\",\"9\":\"54.9\",\"10\":\"2414\",\"11\":\"ohc\",\"12\":\"four\",\"13\":\"122\",\"14\":\"mpfi\",\"15\":\"3.31\",\"16\":\"3.54\",\"17\":\"8.70\",\"18\":\"92\",\"19\":\"4200\",\"20\":\"27\",\"21\":\"32\",\"22\":\"10898.00\"},{\"1\":\"std\",\"2\":\"four\",\"3\":\"hatchback\",\"4\":\"fwd\",\"5\":\"front\",\"6\":\"102.4\",\"7\":\"175.6\",\"8\":\"66.5\",\"9\":\"53.9\",\"10\":\"2458\",\"11\":\"ohc\",\"12\":\"four\",\"13\":\"122\",\"14\":\"mpfi\",\"15\":\"3.31\",\"16\":\"3.54\",\"17\":\"8.70\",\"18\":\"92\",\"19\":\"4200\",\"20\":\"27\",\"21\":\"32\",\"22\":\"11248.00\"},{\"1\":\"std\",\"2\":\"two\",\"3\":\"hatchback\",\"4\":\"rwd\",\"5\":\"front\",\"6\":\"102.9\",\"7\":\"183.5\",\"8\":\"67.7\",\"9\":\"52.0\",\"10\":\"2976\",\"11\":\"dohc\",\"12\":\"six\",\"13\":\"171\",\"14\":\"mpfi\",\"15\":\"3.27\",\"16\":\"3.35\",\"17\":\"9.30\",\"18\":\"161\",\"19\":\"5200\",\"20\":\"20\",\"21\":\"24\",\"22\":\"16558.00\"},{\"1\":\"std\",\"2\":\"two\",\"3\":\"hatchback\",\"4\":\"rwd\",\"5\":\"front\",\"6\":\"102.9\",\"7\":\"183.5\",\"8\":\"67.7\",\"9\":\"52.0\",\"10\":\"3016\",\"11\":\"dohc\",\"12\":\"six\",\"13\":\"171\",\"14\":\"mpfi\",\"15\":\"3.27\",\"16\":\"3.35\",\"17\":\"9.30\",\"18\":\"161\",\"19\":\"5200\",\"20\":\"19\",\"21\":\"24\",\"22\":\"15998.00\"},{\"1\":\"std\",\"2\":\"four\",\"3\":\"sedan\",\"4\":\"rwd\",\"5\":\"front\",\"6\":\"104.5\",\"7\":\"187.8\",\"8\":\"66.5\",\"9\":\"54.1\",\"10\":\"3131\",\"11\":\"dohc\",\"12\":\"six\",\"13\":\"171\",\"14\":\"mpfi\",\"15\":\"3.27\",\"16\":\"3.35\",\"17\":\"9.20\",\"18\":\"156\",\"19\":\"5200\",\"20\":\"20\",\"21\":\"24\",\"22\":\"15690.00\"},{\"1\":\"std\",\"2\":\"four\",\"3\":\"wagon\",\"4\":\"rwd\",\"5\":\"front\",\"6\":\"104.5\",\"7\":\"187.8\",\"8\":\"66.5\",\"9\":\"54.1\",\"10\":\"3151\",\"11\":\"dohc\",\"12\":\"six\",\"13\":\"161\",\"14\":\"mpfi\",\"15\":\"3.27\",\"16\":\"3.35\",\"17\":\"9.20\",\"18\":\"156\",\"19\":\"5200\",\"20\":\"19\",\"21\":\"24\",\"22\":\"15750.00\"},{\"1\":\"std\",\"2\":\"two\",\"3\":\"sedan\",\"4\":\"fwd\",\"5\":\"front\",\"6\":\"97.3\",\"7\":\"171.7\",\"8\":\"65.5\",\"9\":\"55.7\",\"10\":\"2209\",\"11\":\"ohc\",\"12\":\"four\",\"13\":\"109\",\"14\":\"mpfi\",\"15\":\"3.19\",\"16\":\"3.40\",\"17\":\"9.00\",\"18\":\"85\",\"19\":\"5250\",\"20\":\"27\",\"21\":\"34\",\"22\":\"7975.00\"},{\"1\":\"std\",\"2\":\"four\",\"3\":\"sedan\",\"4\":\"fwd\",\"5\":\"front\",\"6\":\"97.3\",\"7\":\"171.7\",\"8\":\"65.5\",\"9\":\"55.7\",\"10\":\"2212\",\"11\":\"ohc\",\"12\":\"four\",\"13\":\"109\",\"14\":\"mpfi\",\"15\":\"3.19\",\"16\":\"3.40\",\"17\":\"9.00\",\"18\":\"85\",\"19\":\"5250\",\"20\":\"27\",\"21\":\"34\",\"22\":\"8195.00\"},{\"1\":\"std\",\"2\":\"four\",\"3\":\"sedan\",\"4\":\"fwd\",\"5\":\"front\",\"6\":\"97.3\",\"7\":\"171.7\",\"8\":\"65.5\",\"9\":\"55.7\",\"10\":\"2275\",\"11\":\"ohc\",\"12\":\"four\",\"13\":\"109\",\"14\":\"mpfi\",\"15\":\"3.19\",\"16\":\"3.40\",\"17\":\"9.00\",\"18\":\"85\",\"19\":\"5250\",\"20\":\"27\",\"21\":\"34\",\"22\":\"8495.00\"},{\"1\":\"std\",\"2\":\"four\",\"3\":\"sedan\",\"4\":\"fwd\",\"5\":\"front\",\"6\":\"97.3\",\"7\":\"171.7\",\"8\":\"65.5\",\"9\":\"55.7\",\"10\":\"2300\",\"11\":\"ohc\",\"12\":\"four\",\"13\":\"109\",\"14\":\"mpfi\",\"15\":\"3.19\",\"16\":\"3.40\",\"17\":\"10.00\",\"18\":\"100\",\"19\":\"5500\",\"20\":\"26\",\"21\":\"32\",\"22\":\"9995.00\"},{\"1\":\"std\",\"2\":\"two\",\"3\":\"convertible\",\"4\":\"fwd\",\"5\":\"front\",\"6\":\"94.5\",\"7\":\"159.3\",\"8\":\"64.2\",\"9\":\"55.6\",\"10\":\"2254\",\"11\":\"ohc\",\"12\":\"four\",\"13\":\"109\",\"14\":\"mpfi\",\"15\":\"3.19\",\"16\":\"3.40\",\"17\":\"8.50\",\"18\":\"90\",\"19\":\"5500\",\"20\":\"24\",\"21\":\"29\",\"22\":\"11595.00\"},{\"1\":\"std\",\"2\":\"two\",\"3\":\"hatchback\",\"4\":\"fwd\",\"5\":\"front\",\"6\":\"94.5\",\"7\":\"165.7\",\"8\":\"64.0\",\"9\":\"51.4\",\"10\":\"2221\",\"11\":\"ohc\",\"12\":\"four\",\"13\":\"109\",\"14\":\"mpfi\",\"15\":\"3.19\",\"16\":\"3.40\",\"17\":\"8.50\",\"18\":\"90\",\"19\":\"5500\",\"20\":\"24\",\"21\":\"29\",\"22\":\"9980.00\"},{\"1\":\"std\",\"2\":\"four\",\"3\":\"sedan\",\"4\":\"fwd\",\"5\":\"front\",\"6\":\"100.4\",\"7\":\"180.2\",\"8\":\"66.9\",\"9\":\"55.1\",\"10\":\"2661\",\"11\":\"ohc\",\"12\":\"five\",\"13\":\"136\",\"14\":\"mpfi\",\"15\":\"3.19\",\"16\":\"3.40\",\"17\":\"8.50\",\"18\":\"110\",\"19\":\"5500\",\"20\":\"19\",\"21\":\"24\",\"22\":\"13295.00\"},{\"1\":\"std\",\"2\":\"four\",\"3\":\"wagon\",\"4\":\"fwd\",\"5\":\"front\",\"6\":\"100.4\",\"7\":\"183.1\",\"8\":\"66.9\",\"9\":\"55.1\",\"10\":\"2563\",\"11\":\"ohc\",\"12\":\"four\",\"13\":\"109\",\"14\":\"mpfi\",\"15\":\"3.19\",\"16\":\"3.40\",\"17\":\"9.00\",\"18\":\"88\",\"19\":\"5500\",\"20\":\"25\",\"21\":\"31\",\"22\":\"12290.00\"},{\"1\":\"std\",\"2\":\"four\",\"3\":\"sedan\",\"4\":\"rwd\",\"5\":\"front\",\"6\":\"104.3\",\"7\":\"188.8\",\"8\":\"67.2\",\"9\":\"56.2\",\"10\":\"2912\",\"11\":\"ohc\",\"12\":\"four\",\"13\":\"141\",\"14\":\"mpfi\",\"15\":\"3.78\",\"16\":\"3.15\",\"17\":\"9.50\",\"18\":\"114\",\"19\":\"5400\",\"20\":\"23\",\"21\":\"28\",\"22\":\"12940.00\"},{\"1\":\"std\",\"2\":\"four\",\"3\":\"wagon\",\"4\":\"rwd\",\"5\":\"front\",\"6\":\"104.3\",\"7\":\"188.8\",\"8\":\"67.2\",\"9\":\"57.5\",\"10\":\"3034\",\"11\":\"ohc\",\"12\":\"four\",\"13\":\"141\",\"14\":\"mpfi\",\"15\":\"3.78\",\"16\":\"3.15\",\"17\":\"9.50\",\"18\":\"114\",\"19\":\"5400\",\"20\":\"23\",\"21\":\"28\",\"22\":\"13415.00\"},{\"1\":\"std\",\"2\":\"four\",\"3\":\"sedan\",\"4\":\"rwd\",\"5\":\"front\",\"6\":\"104.3\",\"7\":\"188.8\",\"8\":\"67.2\",\"9\":\"56.2\",\"10\":\"2935\",\"11\":\"ohc\",\"12\":\"four\",\"13\":\"141\",\"14\":\"mpfi\",\"15\":\"3.78\",\"16\":\"3.15\",\"17\":\"9.50\",\"18\":\"114\",\"19\":\"5400\",\"20\":\"24\",\"21\":\"28\",\"22\":\"15985.00\"},{\"1\":\"std\",\"2\":\"four\",\"3\":\"wagon\",\"4\":\"rwd\",\"5\":\"front\",\"6\":\"104.3\",\"7\":\"188.8\",\"8\":\"67.2\",\"9\":\"57.5\",\"10\":\"3042\",\"11\":\"ohc\",\"12\":\"four\",\"13\":\"141\",\"14\":\"mpfi\",\"15\":\"3.78\",\"16\":\"3.15\",\"17\":\"9.50\",\"18\":\"114\",\"19\":\"5400\",\"20\":\"24\",\"21\":\"28\",\"22\":\"16515.00\"},{\"1\":\"turbo\",\"2\":\"four\",\"3\":\"sedan\",\"4\":\"rwd\",\"5\":\"front\",\"6\":\"104.3\",\"7\":\"188.8\",\"8\":\"67.2\",\"9\":\"56.2\",\"10\":\"3045\",\"11\":\"ohc\",\"12\":\"four\",\"13\":\"130\",\"14\":\"mpfi\",\"15\":\"3.62\",\"16\":\"3.15\",\"17\":\"7.50\",\"18\":\"162\",\"19\":\"5100\",\"20\":\"17\",\"21\":\"22\",\"22\":\"18420.00\"},{\"1\":\"turbo\",\"2\":\"four\",\"3\":\"wagon\",\"4\":\"rwd\",\"5\":\"front\",\"6\":\"104.3\",\"7\":\"188.8\",\"8\":\"67.2\",\"9\":\"57.5\",\"10\":\"3157\",\"11\":\"ohc\",\"12\":\"four\",\"13\":\"130\",\"14\":\"mpfi\",\"15\":\"3.62\",\"16\":\"3.15\",\"17\":\"7.50\",\"18\":\"162\",\"19\":\"5100\",\"20\":\"17\",\"21\":\"22\",\"22\":\"18950.00\"},{\"1\":\"std\",\"2\":\"four\",\"3\":\"sedan\",\"4\":\"rwd\",\"5\":\"front\",\"6\":\"109.1\",\"7\":\"188.8\",\"8\":\"68.9\",\"9\":\"55.5\",\"10\":\"2952\",\"11\":\"ohc\",\"12\":\"four\",\"13\":\"141\",\"14\":\"mpfi\",\"15\":\"3.78\",\"16\":\"3.15\",\"17\":\"9.50\",\"18\":\"114\",\"19\":\"5400\",\"20\":\"23\",\"21\":\"28\",\"22\":\"16845.00\"},{\"1\":\"turbo\",\"2\":\"four\",\"3\":\"sedan\",\"4\":\"rwd\",\"5\":\"front\",\"6\":\"109.1\",\"7\":\"188.8\",\"8\":\"68.8\",\"9\":\"55.5\",\"10\":\"3049\",\"11\":\"ohc\",\"12\":\"four\",\"13\":\"141\",\"14\":\"mpfi\",\"15\":\"3.78\",\"16\":\"3.15\",\"17\":\"8.70\",\"18\":\"160\",\"19\":\"5300\",\"20\":\"19\",\"21\":\"25\",\"22\":\"19045.00\"},{\"1\":\"std\",\"2\":\"four\",\"3\":\"sedan\",\"4\":\"rwd\",\"5\":\"front\",\"6\":\"109.1\",\"7\":\"188.8\",\"8\":\"68.9\",\"9\":\"55.5\",\"10\":\"3012\",\"11\":\"ohcv\",\"12\":\"six\",\"13\":\"173\",\"14\":\"mpfi\",\"15\":\"3.58\",\"16\":\"2.87\",\"17\":\"8.80\",\"18\":\"134\",\"19\":\"5500\",\"20\":\"18\",\"21\":\"23\",\"22\":\"21485.00\"},{\"1\":\"turbo\",\"2\":\"four\",\"3\":\"sedan\",\"4\":\"rwd\",\"5\":\"front\",\"6\":\"109.1\",\"7\":\"188.8\",\"8\":\"68.9\",\"9\":\"55.5\",\"10\":\"3062\",\"11\":\"ohc\",\"12\":\"four\",\"13\":\"141\",\"14\":\"mpfi\",\"15\":\"3.78\",\"16\":\"3.15\",\"17\":\"9.50\",\"18\":\"114\",\"19\":\"5400\",\"20\":\"19\",\"21\":\"25\",\"22\":\"22625.00\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n\n```{.r .cell-code}\n# Get glimpse of data\nglimpse(df)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n#> Rows: 181\n#> Columns: 22\n#> $ aspiration       <chr> \"std\", \"std\", \"std\", \"std\", \"std\", \"std\", \"std\", \"std…\n#> $ doornumber       <chr> \"two\", \"two\", \"two\", \"four\", \"four\", \"two\", \"four\", \"…\n#> $ carbody          <chr> \"convertible\", \"convertible\", \"hatchback\", \"sedan\", \"…\n#> $ drivewheel       <chr> \"rwd\", \"rwd\", \"rwd\", \"fwd\", \"4wd\", \"fwd\", \"fwd\", \"fwd…\n#> $ enginelocation   <chr> \"front\", \"front\", \"front\", \"front\", \"front\", \"front\",…\n#> $ wheelbase        <dbl> 88.6, 88.6, 94.5, 99.8, 99.4, 99.8, 105.8, 105.8, 105…\n#> $ carlength        <dbl> 168.8, 168.8, 171.2, 176.6, 176.6, 177.3, 192.7, 192.…\n#> $ carwidth         <dbl> 64.1, 64.1, 65.5, 66.2, 66.4, 66.3, 71.4, 71.4, 71.4,…\n#> $ carheight        <dbl> 48.8, 48.8, 52.4, 54.3, 54.3, 53.1, 55.7, 55.7, 55.9,…\n#> $ curbweight       <dbl> 2548, 2548, 2823, 2337, 2824, 2507, 2844, 2954, 3086,…\n#> $ enginetype       <chr> \"dohc\", \"dohc\", \"ohcv\", \"ohc\", \"ohc\", \"ohc\", \"ohc\", \"…\n#> $ cylindernumber   <chr> \"four\", \"four\", \"six\", \"four\", \"five\", \"five\", \"five\"…\n#> $ enginesize       <dbl> 130, 130, 152, 109, 136, 136, 136, 136, 131, 131, 108…\n#> $ fuelsystem       <chr> \"mpfi\", \"mpfi\", \"mpfi\", \"mpfi\", \"mpfi\", \"mpfi\", \"mpfi…\n#> $ boreratio        <dbl> 3.47, 3.47, 2.68, 3.19, 3.19, 3.19, 3.19, 3.19, 3.13,…\n#> $ stroke           <dbl> 2.68, 2.68, 3.47, 3.40, 3.40, 3.40, 3.40, 3.40, 3.40,…\n#> $ compressionratio <dbl> 9.00, 9.00, 9.00, 10.00, 8.00, 8.50, 8.50, 8.50, 8.30…\n#> $ horsepower       <dbl> 111, 111, 154, 102, 115, 110, 110, 110, 140, 160, 101…\n#> $ peakrpm          <dbl> 5000, 5000, 5000, 5500, 5500, 5500, 5500, 5500, 5500,…\n#> $ citympg          <dbl> 21, 21, 19, 24, 18, 19, 19, 19, 17, 16, 23, 23, 21, 2…\n#> $ highwaympg       <dbl> 27, 27, 26, 30, 22, 25, 25, 25, 20, 22, 29, 29, 28, 2…\n#> $ price            <dbl> 13495.00, 16500.00, 16500.00, 13950.00, 17450.00, 152…\n```\n:::\n\n```{.r .cell-code}\nsummary(df, digits = 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n#>   aspiration         doornumber          carbody           drivewheel       \n#>  Length:181         Length:181         Length:181         Length:181        \n#>  Class :character   Class :character   Class :character   Class :character  \n#>  Mode  :character   Mode  :character   Mode  :character   Mode  :character  \n#>                                                                             \n#>                                                                             \n#>                                                                             \n#>  enginelocation       wheelbase       carlength      carwidth      carheight   \n#>  Length:181         Min.   : 86.6   Min.   :141   Min.   :60.3   Min.   :47.8  \n#>  Class :character   1st Qu.: 94.5   1st Qu.:166   1st Qu.:64.0   1st Qu.:52.0  \n#>  Mode  :character   Median : 96.5   Median :173   Median :65.4   Median :53.7  \n#>                     Mean   : 98.2   Mean   :173   Mean   :65.7   Mean   :53.6  \n#>                     3rd Qu.:100.4   3rd Qu.:180   3rd Qu.:66.5   3rd Qu.:55.5  \n#>                     Max.   :120.9   Max.   :208   Max.   :72.3   Max.   :59.8  \n#>    curbweight    enginetype        cylindernumber       enginesize \n#>  Min.   :1488   Length:181         Length:181         Min.   : 61  \n#>  1st Qu.:2122   Class :character   Class :character   1st Qu.: 98  \n#>  Median :2410   Mode  :character   Mode  :character   Median :120  \n#>  Mean   :2521                                         Mean   :127  \n#>  3rd Qu.:2910                                         3rd Qu.:141  \n#>  Max.   :4066                                         Max.   :326  \n#>   fuelsystem          boreratio        stroke     compressionratio\n#>  Length:181         Min.   :2.54   Min.   :2.07   Min.   : 7.00   \n#>  Class :character   1st Qu.:3.15   1st Qu.:3.08   1st Qu.: 8.50   \n#>  Mode  :character   Median :3.31   Median :3.23   Median : 9.00   \n#>                     Mean   :3.32   Mean   :3.23   Mean   : 8.85   \n#>                     3rd Qu.:3.59   3rd Qu.:3.40   3rd Qu.: 9.40   \n#>                     Max.   :3.94   Max.   :4.17   Max.   :11.50   \n#>    horsepower     peakrpm        citympg       highwaympg       price      \n#>  Min.   : 48   Min.   :4200   Min.   :13.0   Min.   :16.0   Min.   : 5118  \n#>  1st Qu.: 70   1st Qu.:4800   1st Qu.:19.0   1st Qu.:25.0   1st Qu.: 7609  \n#>  Median : 95   Median :5200   Median :24.0   Median :30.0   Median : 9980  \n#>  Mean   :106   Mean   :5182   Mean   :24.8   Mean   :30.5   Mean   :12999  \n#>  3rd Qu.:116   3rd Qu.:5500   3rd Qu.:30.0   3rd Qu.:34.0   3rd Qu.:16430  \n#>  Max.   :288   Max.   :6600   Max.   :49.0   Max.   :54.0   Max.   :45400\n```\n:::\n\n```{.r .cell-code}\n# Select only numeric columns\ndf_numeric <- df[sapply(df, is.numeric)]\n\n# Calculate correlation matrix\ncor(df_numeric)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n#>                    wheelbase   carlength   carwidth   carheight curbweight\n#> wheelbase         1.00000000  0.86117385  0.7697984  0.54019069  0.7367123\n#> carlength         0.86117385  1.00000000  0.8264703  0.44081316  0.8660053\n#> carwidth          0.76979836  0.82647026  1.0000000  0.20488138  0.8480000\n#> carheight         0.54019069  0.44081316  0.2048814  1.00000000  0.2141918\n#> curbweight        0.73671231  0.86600528  0.8480000  0.21419176  1.0000000\n#> enginesize        0.55411851  0.68017071  0.7431094 -0.02315796  0.8664640\n#> boreratio         0.46436865  0.60094354  0.5515756  0.13853090  0.6382900\n#> stroke            0.07182428  0.06571525  0.1143203 -0.15074728  0.1003967\n#> compressionratio -0.25528942 -0.25098987 -0.2497246 -0.04784995 -0.3108351\n#> horsepower        0.40436893  0.59890956  0.6971702 -0.09471443  0.8176250\n#> peakrpm          -0.21992786 -0.19115857 -0.1086424 -0.15338356 -0.1596062\n#> citympg          -0.58337119 -0.78122590 -0.7392601 -0.15044099 -0.8727123\n#> highwaympg       -0.62686055 -0.78886402 -0.7501573 -0.18342575 -0.8873144\n#> price             0.55547499  0.67307358  0.7430132  0.07452058  0.8340814\n#>                   enginesize  boreratio      stroke compressionratio\n#> wheelbase         0.55411851  0.4643687  0.07182428      -0.25528942\n#> carlength         0.68017071  0.6009435  0.06571525      -0.25098987\n#> carwidth          0.74310940  0.5515756  0.11432033      -0.24972464\n#> carheight        -0.02315796  0.1385309 -0.15074728      -0.04784995\n#> curbweight        0.86646404  0.6382900  0.10039673      -0.31083510\n#> enginesize        1.00000000  0.5779073  0.18198111      -0.16132409\n#> boreratio         0.57790729  1.0000000 -0.10077211      -0.19600019\n#> stroke            0.18198111 -0.1007721  1.00000000      -0.30056815\n#> compressionratio -0.16132409 -0.1960002 -0.30056815       1.00000000\n#> horsepower        0.84661455  0.5917398  0.11169001      -0.22352509\n#> peakrpm          -0.18477648 -0.2363817  0.06779511       0.15590249\n#> citympg          -0.74373969 -0.6185363 -0.09158746       0.43789655\n#> highwaympg       -0.75541425 -0.6086412 -0.07422008       0.44866322\n#> price             0.88970342  0.5540692  0.03082326      -0.17646152\n#>                   horsepower     peakrpm     citympg  highwaympg       price\n#> wheelbase         0.40436893 -0.21992786 -0.58337119 -0.62686055  0.55547499\n#> carlength         0.59890956 -0.19115857 -0.78122590 -0.78886402  0.67307358\n#> carwidth          0.69717017 -0.10864244 -0.73926008 -0.75015733  0.74301316\n#> carheight        -0.09471443 -0.15338356 -0.15044099 -0.18342575  0.07452058\n#> curbweight        0.81762499 -0.15960618 -0.87271235 -0.88731441  0.83408139\n#> enginesize        0.84661455 -0.18477648 -0.74373969 -0.75541425  0.88970342\n#> boreratio         0.59173978 -0.23638175 -0.61853627 -0.60864116  0.55406923\n#> stroke            0.11169001  0.06779511 -0.09158746 -0.07422008  0.03082326\n#> compressionratio -0.22352509  0.15590249  0.43789655  0.44866322 -0.17646152\n#> horsepower        1.00000000  0.08277528 -0.80612428 -0.77717065  0.84009827\n#> peakrpm           0.08277528  1.00000000  0.02610522  0.05111792 -0.02085359\n#> citympg          -0.80612428  0.02610522  1.00000000  0.97537685 -0.74198802\n#> highwaympg       -0.77717065  0.05111792  0.97537685  1.00000000 -0.74079733\n#> price             0.84009827 -0.02085359 -0.74198802 -0.74079733  1.00000000\n```\n:::\n:::\n\n\n> To view the data type in the DataFrame.\n\n\n::: {.cell hash='03_regression_cache/html/unnamed-chunk-4_aabb303c8cb78b82a229b8dcdf599729'}\n\n```{.r .cell-code}\nstr(df)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n#> tibble [181 × 22] (S3: tbl_df/tbl/data.frame)\n#>  $ aspiration      : chr [1:181] \"std\" \"std\" \"std\" \"std\" ...\n#>  $ doornumber      : chr [1:181] \"two\" \"two\" \"two\" \"four\" ...\n#>  $ carbody         : chr [1:181] \"convertible\" \"convertible\" \"hatchback\" \"sedan\" ...\n#>  $ drivewheel      : chr [1:181] \"rwd\" \"rwd\" \"rwd\" \"fwd\" ...\n#>  $ enginelocation  : chr [1:181] \"front\" \"front\" \"front\" \"front\" ...\n#>  $ wheelbase       : num [1:181] 88.6 88.6 94.5 99.8 99.4 ...\n#>  $ carlength       : num [1:181] 169 169 171 177 177 ...\n#>  $ carwidth        : num [1:181] 64.1 64.1 65.5 66.2 66.4 66.3 71.4 71.4 71.4 67.9 ...\n#>  $ carheight       : num [1:181] 48.8 48.8 52.4 54.3 54.3 53.1 55.7 55.7 55.9 52 ...\n#>  $ curbweight      : num [1:181] 2548 2548 2823 2337 2824 ...\n#>  $ enginetype      : chr [1:181] \"dohc\" \"dohc\" \"ohcv\" \"ohc\" ...\n#>  $ cylindernumber  : chr [1:181] \"four\" \"four\" \"six\" \"four\" ...\n#>  $ enginesize      : num [1:181] 130 130 152 109 136 136 136 136 131 131 ...\n#>  $ fuelsystem      : chr [1:181] \"mpfi\" \"mpfi\" \"mpfi\" \"mpfi\" ...\n#>  $ boreratio       : num [1:181] 3.47 3.47 2.68 3.19 3.19 3.19 3.19 3.19 3.13 3.13 ...\n#>  $ stroke          : num [1:181] 2.68 2.68 3.47 3.4 3.4 3.4 3.4 3.4 3.4 3.4 ...\n#>  $ compressionratio: num [1:181] 9 9 9 10 8 8.5 8.5 8.5 8.3 7 ...\n#>  $ horsepower      : num [1:181] 111 111 154 102 115 110 110 110 140 160 ...\n#>  $ peakrpm         : num [1:181] 5000 5000 5000 5500 5500 5500 5500 5500 5500 5500 ...\n#>  $ citympg         : num [1:181] 21 21 19 24 18 19 19 19 17 16 ...\n#>  $ highwaympg      : num [1:181] 27 27 26 30 22 25 25 25 20 22 ...\n#>  $ price           : num [1:181] 13495 16500 16500 13950 17450 ...\n```\n:::\n:::\n\n* We have \"chr\" and \"num\" as data types in our dataset.\n\n> Numbers and strings are different data types and they are treated differently.\n\n* Numbers: These are numerical values that can be integers or doubles (for decimal numbers). You can perform arithmetic operations on numbers. For example, you can define a number as num <- 10 or num <- 10.5.\n\n* Strings (Character): These are sequences of characters. Strings are used to store text data. You can perform operations like concatenation on strings, but you cannot perform arithmetic operations. You can define a string as str <- \"Hello, World!\"\n\n# Task 3\n\n------------------------------------------------------------------------\n\n\n::: {.cell hash='03_regression_cache/html/unnamed-chunk-5_cb6ea9a97f8e5939332eac9ee3e41b49'}\n\n```{.r .cell-code}\nlm_model <- lm(price ~ ., data = df)\n\nsummary(lm_model)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n#> \n#> Call:\n#> lm(formula = price ~ ., data = df)\n#> \n#> Residuals:\n#>    Min     1Q Median     3Q    Max \n#>  -5662  -1120      0    798   9040 \n#> \n#> Coefficients:\n#>                        Estimate Std. Error t value Pr(>|t|)    \n#> (Intercept)          -36269.965  15460.866  -2.346 0.020354 *  \n#> aspirationturbo        1846.206   1041.391   1.773 0.078386 .  \n#> doornumbertwo           242.523    571.929   0.424 0.672172    \n#> carbodyhardtop        -3691.743   1424.825  -2.591 0.010561 *  \n#> carbodyhatchback      -3344.335   1238.359  -2.701 0.007757 ** \n#> carbodysedan          -2292.820   1356.014  -1.691 0.093043 .  \n#> carbodywagon          -3427.921   1490.285  -2.300 0.022885 *  \n#> drivewheelfwd          -504.564   1076.623  -0.469 0.640030    \n#> drivewheelrwd           -15.446   1268.070  -0.012 0.990299    \n#> enginelocationrear     6643.492   2572.275   2.583 0.010806 *  \n#> wheelbase               -30.197     92.776  -0.325 0.745294    \n#> carlength               -29.740     51.672  -0.576 0.565824    \n#> carwidth                731.819    244.533   2.993 0.003258 ** \n#> carheight               123.195    134.607   0.915 0.361617    \n#> curbweight                2.612      1.781   1.467 0.144706    \n#> enginetypedohcv       -8541.957   4749.685  -1.798 0.074219 .  \n#> enginetypel             978.748   1786.384   0.548 0.584619    \n#> enginetypeohc          3345.252    933.001   3.585 0.000461 ***\n#> enginetypeohcf          972.919   1625.631   0.598 0.550462    \n#> enginetypeohcv        -6222.322   1236.415  -5.033 1.43e-06 ***\n#> cylindernumberfive   -11724.540   3019.192  -3.883 0.000157 ***\n#> cylindernumberfour   -11549.326   3177.177  -3.635 0.000387 ***\n#> cylindernumbersix     -7151.398   2247.230  -3.182 0.001793 ** \n#> cylindernumberthree   -4318.929   4688.833  -0.921 0.358545    \n#> cylindernumbertwelve -11122.209   4196.494  -2.650 0.008946 ** \n#> enginesize              125.934     26.541   4.745 5.00e-06 ***\n#> fuelsystem2bbl          177.136    883.615   0.200 0.841400    \n#> fuelsystemmfi         -3041.018   2576.996  -1.180 0.239934    \n#> fuelsystemmpfi          359.278   1001.529   0.359 0.720326    \n#> fuelsystemspdi        -2543.890   1363.546  -1.866 0.064140 .  \n#> fuelsystemspfi          514.766   2499.229   0.206 0.837107    \n#> boreratio             -1306.740   1642.221  -0.796 0.427516    \n#> stroke                -4527.137    922.732  -4.906 2.49e-06 ***\n#> compressionratio       -737.901    555.960  -1.327 0.186539    \n#> horsepower               10.293     22.709   0.453 0.651035    \n#> peakrpm                   2.526      0.634   3.983 0.000108 ***\n#> citympg                 -90.352    166.647  -0.542 0.588538    \n#> highwaympg              154.858    167.148   0.926 0.355761    \n#> ---\n#> Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n#> \n#> Residual standard error: 2189 on 143 degrees of freedom\n#> Multiple R-squared:  0.9415,\tAdjusted R-squared:  0.9264 \n#> F-statistic: 62.21 on 37 and 143 DF,  p-value: < 2.2e-16\n```\n:::\n:::\n\n\nThe more '*' there are, the more important the factors are for the car's price. Looking at the table, we can say these things really matter when it comes to deciding how much the car costs.\n\n\n# Task 4\n\n------------------------------------------------------------------------\n\nI would like to select **peakrpm** as a Regressor.\n\n* **Data Type**: As observed in the linear regression summary, the **peakrpm** variable is of numeric type.\n\n* **Impact on Price**: The coefficient for **peakrpm** is 2.526. This signifies that for every one-unit increase in size, the expected price increase is 2.526 units, while holding other variables constant.\n\n* **Statistical Significance**: The p-value is remarkably low at 0.000108, suggesting high statistical significance. This implies that the influence of **peakrpm** on the **Price** is substantial.\n\n# Task 5\n\n------------------------------------------------------------------------\n\n\n::: {.cell hash='03_regression_cache/html/unnamed-chunk-6_fbedcaa59ce5a56f2571cba55f79bbb9'}\n\n```{.r .cell-code}\nlibrary(dplyr)\n\ndf <- mutate(df, seat_heating = TRUE)\n\nmodel <- lm(price ~ . + seat_heating, data = df)\n\nsummary(model)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n#> \n#> Call:\n#> lm(formula = price ~ . + seat_heating, data = df)\n#> \n#> Residuals:\n#>    Min     1Q Median     3Q    Max \n#>  -5662  -1120      0    798   9040 \n#> \n#> Coefficients: (1 not defined because of singularities)\n#>                        Estimate Std. Error t value Pr(>|t|)    \n#> (Intercept)          -36269.965  15460.866  -2.346 0.020354 *  \n#> aspirationturbo        1846.206   1041.391   1.773 0.078386 .  \n#> doornumbertwo           242.523    571.929   0.424 0.672172    \n#> carbodyhardtop        -3691.743   1424.825  -2.591 0.010561 *  \n#> carbodyhatchback      -3344.335   1238.359  -2.701 0.007757 ** \n#> carbodysedan          -2292.820   1356.014  -1.691 0.093043 .  \n#> carbodywagon          -3427.921   1490.285  -2.300 0.022885 *  \n#> drivewheelfwd          -504.564   1076.623  -0.469 0.640030    \n#> drivewheelrwd           -15.446   1268.070  -0.012 0.990299    \n#> enginelocationrear     6643.492   2572.275   2.583 0.010806 *  \n#> wheelbase               -30.197     92.776  -0.325 0.745294    \n#> carlength               -29.740     51.672  -0.576 0.565824    \n#> carwidth                731.819    244.533   2.993 0.003258 ** \n#> carheight               123.195    134.607   0.915 0.361617    \n#> curbweight                2.612      1.781   1.467 0.144706    \n#> enginetypedohcv       -8541.957   4749.685  -1.798 0.074219 .  \n#> enginetypel             978.748   1786.384   0.548 0.584619    \n#> enginetypeohc          3345.252    933.001   3.585 0.000461 ***\n#> enginetypeohcf          972.919   1625.631   0.598 0.550462    \n#> enginetypeohcv        -6222.322   1236.415  -5.033 1.43e-06 ***\n#> cylindernumberfive   -11724.540   3019.192  -3.883 0.000157 ***\n#> cylindernumberfour   -11549.326   3177.177  -3.635 0.000387 ***\n#> cylindernumbersix     -7151.398   2247.230  -3.182 0.001793 ** \n#> cylindernumberthree   -4318.929   4688.833  -0.921 0.358545    \n#> cylindernumbertwelve -11122.209   4196.494  -2.650 0.008946 ** \n#> enginesize              125.934     26.541   4.745 5.00e-06 ***\n#> fuelsystem2bbl          177.136    883.615   0.200 0.841400    \n#> fuelsystemmfi         -3041.018   2576.996  -1.180 0.239934    \n#> fuelsystemmpfi          359.278   1001.529   0.359 0.720326    \n#> fuelsystemspdi        -2543.890   1363.546  -1.866 0.064140 .  \n#> fuelsystemspfi          514.766   2499.229   0.206 0.837107    \n#> boreratio             -1306.740   1642.221  -0.796 0.427516    \n#> stroke                -4527.137    922.732  -4.906 2.49e-06 ***\n#> compressionratio       -737.901    555.960  -1.327 0.186539    \n#> horsepower               10.293     22.709   0.453 0.651035    \n#> peakrpm                   2.526      0.634   3.983 0.000108 ***\n#> citympg                 -90.352    166.647  -0.542 0.588538    \n#> highwaympg              154.858    167.148   0.926 0.355761    \n#> seat_heatingTRUE             NA         NA      NA       NA    \n#> ---\n#> Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n#> \n#> Residual standard error: 2189 on 143 degrees of freedom\n#> Multiple R-squared:  0.9415,\tAdjusted R-squared:  0.9264 \n#> F-statistic: 62.21 on 37 and 143 DF,  p-value: < 2.2e-16\n```\n:::\n:::\n\n\nSince `seat_heating` is a binary variable with the same value for all observations, it will not have any predictive power in the model. The coefficient for `seat_heating` will be `NA`, and the t-value and p-value will also be `NA`. This is because a variable with a single value does not provide any information that can be used to predict the dependent variable.",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"../../site_libs/pagedtable-1.1/css/pagedtable.css\" rel=\"stylesheet\" />\r\n<script src=\"../../site_libs/pagedtable-1.1/js/pagedtable.js\"></script>\r\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}